--
-- PostgreSQL database dump
--

\restrict c32zyziezKNevcbsMO2YP6kstFfyR6XvZf3u3wj7CO5gdZDioKmOA3aCh1lmDyl

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg12+1)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: shop_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_category (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL
);


--
-- Name: shop_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_coupon; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_coupon (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    discount integer NOT NULL,
    active boolean NOT NULL,
    valid_from timestamp with time zone NOT NULL,
    valid_to timestamp with time zone NOT NULL,
    CONSTRAINT shop_coupon_discount_check CHECK ((discount >= 0))
);


--
-- Name: shop_coupon_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_coupon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_coupon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_favorite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_favorite (
    id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: shop_favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_order (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    address character varying(255) NOT NULL,
    created timestamp with time zone NOT NULL,
    paid boolean NOT NULL,
    user_id integer,
    comment text,
    payment_method character varying(10) NOT NULL
);


--
-- Name: shop_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_orderitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_orderitem (
    id bigint NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT shop_orderitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: shop_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_otpcode; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_otpcode (
    id bigint NOT NULL,
    code character varying(6) NOT NULL,
    created timestamp with time zone NOT NULL,
    is_used boolean NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: shop_otpcode_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_otpcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_otpcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    image character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    available boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: shop_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_profile (
    id bigint NOT NULL,
    phone character varying(20) NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: shop_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shop_review (
    id bigint NOT NULL,
    text text NOT NULL,
    rating integer NOT NULL,
    created timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT shop_review_rating_check CHECK ((rating >= 0))
);


--
-- Name: shop_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shop_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Категория	7	add_category
26	Can change Категория	7	change_category
27	Can delete Категория	7	delete_category
28	Can view Категория	7	view_category
29	Can add Товар	8	add_product
30	Can change Товар	8	change_product
31	Can delete Товар	8	delete_product
32	Can view Товар	8	view_product
33	Can add Заказ	9	add_order
34	Can change Заказ	9	change_order
35	Can delete Заказ	9	delete_order
36	Can view Заказ	9	view_order
37	Can add order item	10	add_orderitem
38	Can change order item	10	change_orderitem
39	Can delete order item	10	delete_orderitem
40	Can view order item	10	view_orderitem
41	Can add Избранное	11	add_favorite
42	Can change Избранное	11	change_favorite
43	Can delete Избранное	11	delete_favorite
44	Can view Избранное	11	view_favorite
45	Can add Отзыв	12	add_review
46	Can change Отзыв	12	change_review
47	Can delete Отзыв	12	delete_review
48	Can view Отзыв	12	view_review
49	Can add Купон	13	add_coupon
50	Can change Купон	13	change_coupon
51	Can delete Купон	13	delete_coupon
52	Can view Купон	13	view_coupon
53	Can add profile	14	add_profile
54	Can change profile	14	change_profile
55	Can delete profile	14	delete_profile
56	Can view profile	14	view_profile
57	Can add otp code	15	add_otpcode
58	Can change otp code	15	change_otpcode
59	Can delete otp code	15	delete_otpcode
60	Can view otp code	15	view_otpcode
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
9	pbkdf2_sha256$1000000$0d8Ol1mgjQnJgtz7TGTuY2$ZAlZ+eWEAG1KL6jAB1hadwK0CJmRPIWA+zOu438vwhM=	2026-05-04 08:04:55.24994+00	f	paypal83582	Лук		paypal83582@gmail.com	f	t	2026-05-04 08:04:53.131955+00
8	pbkdf2_sha256$1000000$kx6W77T30EbcZHcrJxt7C0$b/8A9jL0Fx4aw22bfv9aDji3hxAiCqA+Tv99Z3epTfM=	2026-05-04 12:14:38.661422+00	f	gemini91551	Гемини		gemini91551@gmail.com	f	t	2026-05-04 06:28:21.191826+00
10	pbkdf2_sha256$1000000$XjytSyrpVJwPsSPZ6XwMj6$bU35kXEgM19iwTRyzllZIQ3i1Bv72JY3Z5Fr966eCXQ=	2026-05-05 06:06:26.608267+00	f	boostyjafar	5		boostyjafar@gmail.com	f	t	2026-05-05 06:06:24.401345+00
7	pbkdf2_sha256$1000000$3xmRZfO7COMpxG11AjNloB$yloxzpuxITc4co25MOtrOR3XwXQl02UR3a7Y5T+u5Sg=	2026-05-06 04:33:28.192387+00	t	admin			tympler34@example.com	t	t	2026-05-04 05:47:48.828831+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-05-04 05:55:47.580991+00	1	Декоративные кустарники	1	[{"added": {}}]	7	7
2	2026-05-04 05:56:00.103426+00	2	Лиственные	1	[{"added": {}}]	7	7
3	2026-05-04 05:56:10.394401+00	3	Плодовые	1	[{"added": {}}]	7	7
4	2026-05-04 05:56:25.811485+00	4	Тропические	1	[{"added": {}}]	7	7
5	2026-05-04 05:56:33.527506+00	5	Хвойные	1	[{"added": {}}]	7	7
6	2026-05-04 05:57:30.435472+00	1	SALE20 (−10%)	1	[{"added": {}}]	13	7
7	2026-05-04 05:58:31.984078+00	1	Барбарис	1	[{"added": {}}]	8	7
8	2026-05-04 05:59:04.832812+00	2	Береза	1	[{"added": {}}]	8	7
9	2026-05-04 05:59:37.899195+00	3	Венге	1	[{"added": {}}]	8	7
10	2026-05-04 06:00:11.094117+00	4	Вишня	1	[{"added": {}}]	8	7
11	2026-05-04 06:00:48.987613+00	5	Груша	1	[{"added": {}}]	8	7
12	2026-05-04 06:01:18.18507+00	6	Дуб	1	[{"added": {}}]	8	7
13	2026-05-04 06:01:59.088234+00	7	Дёрен	1	[{"added": {}}]	8	7
14	2026-05-04 06:02:40.781218+00	8	Ель	1	[{"added": {}}]	8	7
15	2026-05-04 06:03:22.164083+00	9	Кедр	1	[{"added": {}}]	8	7
16	2026-05-04 06:03:52.998028+00	10	Клён	1	[{"added": {}}]	8	7
17	2026-05-04 06:04:31.221815+00	11	Липа	1	[{"added": {}}]	8	7
18	2026-05-04 06:05:18.418284+00	12	Лиственница	1	[{"added": {}}]	8	7
19	2026-05-04 06:10:01.882035+00	13	Махогони	1	[{"added": {}}]	8	7
20	2026-05-04 06:10:33.691764+00	14	Палисандр	1	[{"added": {}}]	8	7
21	2026-05-04 06:11:00.483759+00	15	Пихта	1	[{"added": {}}]	8	7
22	2026-05-04 06:11:41.227954+00	16	Сирень	1	[{"added": {}}]	8	7
23	2026-05-04 06:12:17.421071+00	17	Слива	1	[{"added": {}}]	8	7
24	2026-05-04 06:12:49.540852+00	18	Сосна	1	[{"added": {}}]	8	7
25	2026-05-04 06:13:22.494418+00	19	Спирея	1	[{"added": {}}]	8	7
26	2026-05-04 06:13:48.938948+00	20	Тик	1	[{"added": {}}]	8	7
27	2026-05-04 06:14:11.398549+00	21	Черешня	1	[{"added": {}}]	8	7
28	2026-05-04 06:14:50.936177+00	22	Яблоня	1	[{"added": {}}]	8	7
29	2026-05-04 06:15:20.089032+00	23	Ясень	1	[{"added": {}}]	8	7
30	2026-05-04 11:21:21.000047+00	1	Барбарис	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
31	2026-05-04 11:32:34.378956+00	2	Береза	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
32	2026-05-04 11:34:38.418159+00	4	Вишня	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
33	2026-05-04 11:35:14.038247+00	5	Груша	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
34	2026-05-04 11:35:53.596664+00	7	Дёрен	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
35	2026-05-04 11:36:27.458462+00	6	Дуб	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
36	2026-05-04 11:37:27.601779+00	10	Клён	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
37	2026-05-04 11:41:24.527714+00	15	Пихта	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
38	2026-05-04 11:42:03.603199+00	8	Ель	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
39	2026-05-04 11:42:38.64478+00	9	Кедр	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
40	2026-05-04 11:43:14.173615+00	11	Липа	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
41	2026-05-04 11:43:51.040742+00	12	Лиственница	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
42	2026-05-04 11:44:28.451796+00	23	Ясень	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
43	2026-05-04 11:45:36.423637+00	22	Яблоня	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
44	2026-05-04 11:47:08.35032+00	21	Черешня	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
45	2026-05-04 11:55:32.228507+00	20	Тик	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
46	2026-05-04 11:55:59.30462+00	19	Спирея	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
47	2026-05-04 11:56:47.388304+00	18	Сосна	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
48	2026-05-04 11:57:42.478371+00	17	Слива	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
49	2026-05-04 11:58:28.305979+00	16	Сирень	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
50	2026-05-04 12:11:45.816905+00	13	Махогони	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	8	7
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	shop	category
8	shop	product
9	shop	order
10	shop	orderitem
11	shop	favorite
12	shop	review
13	shop	coupon
14	shop	profile
15	shop	otpcode
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-04 03:52:02.990225+00
2	auth	0001_initial	2026-05-04 03:52:03.194704+00
3	admin	0001_initial	2026-05-04 03:52:03.28647+00
4	admin	0002_logentry_remove_auto_add	2026-05-04 03:52:03.293935+00
5	admin	0003_logentry_add_action_flag_choices	2026-05-04 03:52:03.304378+00
6	contenttypes	0002_remove_content_type_name	2026-05-04 03:52:03.317829+00
7	auth	0002_alter_permission_name_max_length	2026-05-04 03:52:03.327555+00
8	auth	0003_alter_user_email_max_length	2026-05-04 03:52:03.336327+00
9	auth	0004_alter_user_username_opts	2026-05-04 03:52:03.344151+00
10	auth	0005_alter_user_last_login_null	2026-05-04 03:52:03.377448+00
11	auth	0006_require_contenttypes_0002	2026-05-04 03:52:03.379862+00
12	auth	0007_alter_validators_add_error_messages	2026-05-04 03:52:03.386325+00
13	auth	0008_alter_user_username_max_length	2026-05-04 03:52:03.396396+00
14	auth	0009_alter_user_last_name_max_length	2026-05-04 03:52:03.40598+00
15	auth	0010_alter_group_name_max_length	2026-05-04 03:52:03.41476+00
16	auth	0011_update_proxy_permissions	2026-05-04 03:52:03.421231+00
17	auth	0012_alter_user_first_name_max_length	2026-05-04 03:52:03.433574+00
18	sessions	0001_initial	2026-05-04 03:52:03.479923+00
19	shop	0001_initial	2026-05-04 03:52:03.494473+00
20	shop	0002_order_orderitem	2026-05-04 03:52:03.580743+00
21	shop	0003_order_user	2026-05-04 03:52:03.592905+00
22	shop	0004_favorite	2026-05-04 03:52:03.610382+00
23	shop	0005_review	2026-05-04 03:52:03.682461+00
24	shop	0006_coupon	2026-05-04 03:52:03.690367+00
25	shop	0007_order_comment	2026-05-04 03:52:03.698983+00
26	shop	0008_alter_order_address	2026-05-04 03:52:03.713467+00
27	shop	0009_alter_order_first_name_alter_order_last_name_and_more	2026-05-04 03:52:03.793633+00
28	shop	0010_order_payment_method	2026-05-04 03:52:03.805124+00
29	shop	0011_profile	2026-05-04 03:52:03.820606+00
30	shop	0012_otpcode	2026-05-04 03:52:03.835418+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7l714xa64fxmtn0ce9uc6x315ouo27an	eyJjYXJ0Ijp7fX0:1wJkMO:PzcXsYBknQMotPpWc4VoopTWZZIvsOzYYBBdODlY7rk	2026-05-18 03:52:44.548318+00
70hzbz29c1d92330xfhmhrfi2shif235	eyJjYXJ0Ijp7fX0:1wK8dM:mqsDM9ckTuq0py5FvhIwnEVr-TukHaw50o3d8nchob4	2026-05-19 05:47:52.51147+00
90f5iqltsu2fhqc5anemslmkhh97fqog	eyJjYXJ0Ijp7fX0:1wJkeQ:8I38-FNfyl2COw1EzAxLnx-tF96jwDY-05OvJlxMLv4	2026-05-18 04:11:22.531134+00
97q7m57u15xhflzoxpng9b1j9v3ad9iw	eyJjYXJ0Ijp7fX0:1wJkeS:VoYes--10vdg31DqUnMDMbcQEh7JfrzxouqxzKYatks	2026-05-18 04:11:24.16475+00
tqfe5qmatz99r559yghvjw0e8tcqoe82	eyJjYXJ0Ijp7fX0:1wJmAH:f95ZRT9Q9auvd7Z5Tah7xNEO7bo-F6kNy_Ile0H43zI	2026-05-18 05:48:21.602879+00
aqvdjr4gxkvmnuf93naxs3658lrhx94o	eyJjYXJ0Ijp7fX0:1wJmAR:rn6KUOGrAmNi3Q8u-FcIL8SgD1n79X-OKo0SVt_H_7Q	2026-05-18 05:48:31.655758+00
f8kea8i0z5zne92ix6bqi5snkcqminf6	eyJjYXJ0Ijp7fX0:1wK8dt:Kx8DtmvCAm1272ixpoCZvzqy8kpsxOy3wGUMZhk0GHk	2026-05-19 05:48:25.690948+00
95oimy80zu8u4g03eaafpof174xzfpbv	eyJjYXJ0Ijp7fX0:1wJrQi:lI14yzzs2NmQbuOjCPe0UAqXOYNp_3WYyZGLT0Ts2ZM	2026-05-18 11:25:40.084403+00
zwdsn1apb47eceighmfafzibz0zlaty4	eyJjYXJ0Ijp7fX0:1wJrQr:oBtnn161j0o3nORQpnxGoTIh0qE8CkWQJR9fUW1em7Y	2026-05-18 11:25:49.685933+00
b8eg1oop2uf9sofo5mgpwrjdxe29zapu	eyJjYXJ0Ijp7fX0:1wK8eG:Fl5pTiFe3l5-WSVLeX2bul3_rC8snI_Xf5amxrMYFls	2026-05-19 05:48:48.483453+00
88q2xkqyh897p5si8k7qj3e9z8x8xebt	eyJjYXJ0Ijp7fX0:1wJpm0:j38BVIlisBLcK88cfsG4pyq3G9i70fsCJkSWqWPGQuQ	2026-05-18 09:39:32.840904+00
r5p4w3r86u95d6io7xke2e8hsnskyuge	eyJjYXJ0Ijp7fX0:1wJpmE:uqW8S2Nief_GMErQWcK7tI8ASjzhJ7oS87tVGaDLL08	2026-05-18 09:39:46.381109+00
r32awagvwxsfuahgltoszq8h0gc5bvjb	eyJjYXJ0Ijp7fX0:1wJuNi:zX1TXH-NupNmgyVM8V3hNBntq4he0jEue30Frcv0Hms	2026-05-18 14:34:46.282233+00
4q6q5dc0mxcj7woue6vt9o52sv3ejvpp	eyJjYXJ0Ijp7fX0:1wJpzU:sN052UR0KDJth8XYTtOwiNzU-kQmv0Z7Jl8eqvXhSSc	2026-05-18 09:53:28.09725+00
iu5mi16i0xfheghhi55o1y3oevueujhm	eyJjYXJ0Ijp7fX0:1wJpzb:c1nzRnco77ehjljmU_iUPjWRZoIqsfkyOG5kNlGSvZo	2026-05-18 09:53:35.872569+00
dvauipupr158lr5kia4efy45kkhyqmoq	eyJjYXJ0Ijp7fX0:1wJuNi:zX1TXH-NupNmgyVM8V3hNBntq4he0jEue30Frcv0Hms	2026-05-18 14:34:46.484139+00
1nlbnyp3ibp45bj7om7h4ba3yaicno4r	eyJjYXJ0Ijp7fX0:1wJrK1:rrr4uo8nQst9pE6j3uPEWLgsCHKCvzplg1ndbOfNtuA	2026-05-18 11:18:45.701073+00
ax01009be50gfmjeitad35sfxgyqgrmr	eyJjYXJ0Ijp7fX0:1wJrK9:kqbP0KF9idF3TTYKZdfy2iyMlLQo2kmcLT_KJwhcZzY	2026-05-18 11:18:53.492154+00
bgaz85f84ebamewoewsz6nogiglf772y	eyJjYXJ0Ijp7fX0:1wJubq:yCtDQPOmj44CbqYCa82cGye_omnLsormQ49bXl3qBvY	2026-05-18 14:49:22.434591+00
qwsgc9avcxwessbkbgkyq69dkud0xh20	eyJjYXJ0Ijp7fX0:1wJubq:yCtDQPOmj44CbqYCa82cGye_omnLsormQ49bXl3qBvY	2026-05-18 14:49:22.622313+00
ihvklqr2sndj2yinv3h3skqxw6r7ong2	eyJjYXJ0Ijp7fX0:1wJue6:MwtxGJT328WRKDRtcmnVhrd0RVC15NsB4dxC1ssttJk	2026-05-18 14:51:42.299214+00
7fzzvg8rrhre80pdf4x40b3yzy2fp8eq	eyJjYXJ0Ijp7IjEzIjp7InF1YW50aXR5IjoxLCJwcmljZSI6IjEwMDAwLjAwIn19fQ:1wJugI:dTraMhtHB8GCZoS9a2V1ZTNkXyXknJJw3qH6rFe_LHQ	2026-05-18 14:53:58.950731+00
g1o44v20x3z6guubaktf26z13cg9irbp	eyJjYXJ0Ijp7fX0:1wJugL:Er45ZqBnVmygRPf0FpJKC3kYpT64MfI7JMUa-1rDxII	2026-05-18 14:54:01.196691+00
a0leqaijqm5r43xc0zghcnhkqjnoy1jz	eyJjYXJ0Ijp7fX0:1wJugn:cL46AGdtJ6L1K0FiRiZubI2I1Ykif-sMCQxhZL8B-9E	2026-05-18 14:54:29.680872+00
f745lnjk3f1u0szn5lj0rzv78aptlkss	eyJjYXJ0Ijp7fX0:1wJuhe:zjoc5sZOaNKj_OZ4D7Yi01PbZhF6SMAJ2Cxb32Ul4T4	2026-05-18 14:55:22.988797+00
23cq6smjfz9zlth16o32d0t1qujkbkqw	eyJjYXJ0Ijp7fX0:1wJuhf:HU2uuAydxVYLIlEGcIp9KlluqP0BNzvXHdIQREC5bvs	2026-05-18 14:55:23.677043+00
6lpecxkf3r1rv4f4dh4yrw372pfc2e3p	eyJjYXJ0Ijp7IjEzIjp7InF1YW50aXR5IjoxLCJwcmljZSI6IjEwMDAwLjAwIn19fQ:1wJuhf:jJ4XM7wC8sCaTwBtIUuTkMgyoF4GoFrFBNBHgksT0kk	2026-05-18 14:55:23.792814+00
6vugnes8vtn3p2cq6ug3j4vykh3vvwa9	eyJjYXJ0Ijp7fX0:1wJuhg:F307-SfBH2zKFRvHI2s9axMAozyn4hGpN266tyy9nuY	2026-05-18 14:55:24.282915+00
86cjkry1r81vya28l8nyanbnkbahoo4o	eyJjYXJ0Ijp7fX0:1wJuhg:F307-SfBH2zKFRvHI2s9axMAozyn4hGpN266tyy9nuY	2026-05-18 14:55:24.481627+00
r2k45p72k7v1n3k2j0lzjpte2ufrnns7	eyJjYXJ0Ijp7fX0:1wJuhg:F307-SfBH2zKFRvHI2s9axMAozyn4hGpN266tyy9nuY	2026-05-18 14:55:24.710264+00
9iqrmpx96cbkoyysu5oql4eggpv0gj6f	eyJjYXJ0Ijp7IjE1Ijp7InF1YW50aXR5IjoxLCJwcmljZSI6IjMwMDAuMDAifX19:1wJuhg:O_WwJuFUqaIeKdB7iwSNYpQNamduieXAO3t8ab1ycvc	2026-05-18 14:55:24.88375+00
vou1e4jmpavzt9ia732xwe3qz3k8hfsp	eyJjYXJ0Ijp7fX0:1wJuhh:oSnohuhWt58yh5a7OWog5iNbW3r_it_DUVOmGo2JnPc	2026-05-18 14:55:25.10486+00
e3t3nbf8sjn6y1fvmmv0oa47mqmlg87q	eyJjYXJ0Ijp7fX0:1wJuhh:oSnohuhWt58yh5a7OWog5iNbW3r_it_DUVOmGo2JnPc	2026-05-18 14:55:25.619597+00
drohwc0wkpuqmly4zg7xtnvl544xi9fc	eyJjYXJ0Ijp7fX0:1wJuhi:EC786-EDOZJmGBrqf5aujZJE66Myw4AqUzv_8QfQWNk	2026-05-18 14:55:26.162667+00
3bke31hfl26td9qvryufo79ipye014nh	eyJjYXJ0Ijp7fX0:1wJuhi:EC786-EDOZJmGBrqf5aujZJE66Myw4AqUzv_8QfQWNk	2026-05-18 14:55:26.624089+00
7al58wwsxj003nn3x85irood5m2jx1jq	eyJjYXJ0Ijp7IjciOnsicXVhbnRpdHkiOjEsInByaWNlIjoiMzc2Ny4wMCJ9fX0:1wJuhj:QoaVwEAVzGX3_7ondh_VGvWCtFSUGdSHMQw_iIBn_jI	2026-05-18 14:55:27.167709+00
pungfiu5o6da40mz2jk89klyjpnw0gv3	eyJjYXJ0Ijp7IjE5Ijp7InF1YW50aXR5IjoxLCJwcmljZSI6IjUwMC4wMCJ9fX0:1wJuhj:56LQNQWOWJw4KIHYMcqH3QMtqJvElK1issaxOA9YEJI	2026-05-18 14:55:27.647862+00
f8ds5zs8mfnur0igoay0k1knk923oa30	eyJjYXJ0Ijp7fX0:1wJuhk:QXqxEf0jpYdKxOuh-KHqr7HRm41grCSW_odEEUxtx-Y	2026-05-18 14:55:28.133626+00
p7og920r9bjlh5h4vn1z7i1aj8p87dfn	eyJjYXJ0Ijp7fX0:1wJuhk:QXqxEf0jpYdKxOuh-KHqr7HRm41grCSW_odEEUxtx-Y	2026-05-18 14:55:28.731022+00
qruo9ikdehlj8b86p563t4i78hr6ur9f	eyJjYXJ0Ijp7fX0:1wJuhl:6e8Cm347QNKriWu4EUwOxAJ0dyDotQp5zqDpM5BHG0I	2026-05-18 14:55:29.213394+00
qkfcu42uwg1n2vb2zv2wlqsab398rgp6	eyJjYXJ0Ijp7fX0:1wJuhm:og0ml8BDAGye5Y3wP_DZB4MJI3DJ_FOPRUJeP5Cz0yU	2026-05-18 14:55:30.080586+00
q36rzmbgwowulxb1icv5se0a04urj9ib	eyJjYXJ0Ijp7IjIiOnsicXVhbnRpdHkiOjEsInByaWNlIjoiMzAwLjAwIn19fQ:1wJuhm:73B9sz8UYXvI8_XfAh1-utU_H4rgL7az87AW1EWpv0o	2026-05-18 14:55:30.400269+00
al1wx82rtcxd1scyj0ece9ny9lxoe6w7	eyJjYXJ0Ijp7fX0:1wJuhm:og0ml8BDAGye5Y3wP_DZB4MJI3DJ_FOPRUJeP5Cz0yU	2026-05-18 14:55:30.879713+00
x9i5dd3cmiwz2xj4dwehyo472f14db0d	eyJjYXJ0Ijp7fX0:1wJuhn:5OQU2wwg1TR1OepAvEEqMUxTj9dD3xj7EgW4DOVsJhM	2026-05-18 14:55:31.531988+00
bagshxcnyniyzenlwgak9g10ma1q4itj	eyJjYXJ0Ijp7fX0:1wJuhn:5OQU2wwg1TR1OepAvEEqMUxTj9dD3xj7EgW4DOVsJhM	2026-05-18 14:55:31.884309+00
cyxnxubls1xqe82iwaw0xlg5n4vz6e97	eyJjYXJ0Ijp7fX0:1wJuho:pOIaJWOD2T9laBCu_4l5pTFfrgQq1W4p-SwZQ4w5qTM	2026-05-18 14:55:32.457635+00
f445nwewenpmpqolwww5z5449vd8z6j6	eyJjYXJ0Ijp7fX0:1wJuhp:MCEm0S-83oTIoYnyDPRI9YPQhslR2EtizmYjbnn8nJY	2026-05-18 14:55:33.080178+00
7p41qg7mnqotpzqbrz0xjq9v2768qqkh	eyJjYXJ0Ijp7fX0:1wJuhp:MCEm0S-83oTIoYnyDPRI9YPQhslR2EtizmYjbnn8nJY	2026-05-18 14:55:33.481382+00
4gpn7pdk9hmimkttjupif4t20yc8ix3l	eyJjYXJ0Ijp7fX0:1wJuhp:MCEm0S-83oTIoYnyDPRI9YPQhslR2EtizmYjbnn8nJY	2026-05-18 14:55:33.904704+00
9d40zhx12ylptv6uwyi8uo7ewulhl9zb	eyJjYXJ0Ijp7fX0:1wJuhq:cihYg7n-LodA8UAJevhAxxJ9MTq2sz32XkPdSomzZpY	2026-05-18 14:55:34.390587+00
obfgus9grusoba6bikgjys6swthzoesv	eyJjYXJ0Ijp7fX0:1wJuhs:Zjv82woPzkO1SRRIllpVyKWKin_qlfWjiPfOzdqkeUs	2026-05-18 14:55:36.396983+00
6ssqk7kh70lm1zemef9rnt57mw459uyv	eyJjYXJ0Ijp7IjIwIjp7InF1YW50aXR5IjoxLCJwcmljZSI6IjI1NjUuMDAifX19:1wJujW:cNtaFxow1VAtztowUso9TJY0Xmc2pmI5OrmXlZyqFfU	2026-05-18 14:57:18.658337+00
4ic91skt4vvvxjhm8q2rnxkz70y5joyb	eyJjYXJ0Ijp7IjE0Ijp7InF1YW50aXR5IjoxLCJwcmljZSI6IjgwMDAuMDAifX19:1wJujX:dPuaLiAs8Jzn1ZT0Y4ySNMJ3EaVRz-fZCUwE7eN9NCw	2026-05-18 14:57:19.155391+00
8bso4lc17h0bae213481t18zeza1y5mi	eyJjYXJ0Ijp7fX0:1wJujX:20xDe1LhvXby_1Lfh5DuijM4yps5h3RrOSwi7zF3BXk	2026-05-18 14:57:19.301814+00
tczzlnuokjgfx0buofag2gd38rm6ztn9	eyJjYXJ0Ijp7fX0:1wJujX:20xDe1LhvXby_1Lfh5DuijM4yps5h3RrOSwi7zF3BXk	2026-05-18 14:57:19.484711+00
elw5y0f8vqu51l19a3vkadpxul0kvhh8	eyJjYXJ0Ijp7fX0:1wJujY:l18UUCPcVGbUvWDJ_KJU0d3_Y7cYvJmvjf49Grl855M	2026-05-18 14:57:20.093696+00
ztzykfpwgmhp9188vnxacmdtew09pw7c	eyJjYXJ0Ijp7fX0:1wJujY:l18UUCPcVGbUvWDJ_KJU0d3_Y7cYvJmvjf49Grl855M	2026-05-18 14:57:20.18726+00
es62b0hz11u56v64aw40lv833tqdrkq5	eyJjYXJ0Ijp7fX0:1wJujY:l18UUCPcVGbUvWDJ_KJU0d3_Y7cYvJmvjf49Grl855M	2026-05-18 14:57:20.476707+00
0g4xd7hp7sa0gz2md7htp7c28fnvyhlp	eyJjYXJ0Ijp7fX0:1wJujZ:SARHAAKIrPi_7AI62lr_WvlEoMgk4cuYs0-zxsxHAY0	2026-05-18 14:57:21.456612+00
moo5944okwsem6ijc2p7ljkf41yl3r7f	eyJjYXJ0Ijp7fX0:1wJujZ:SARHAAKIrPi_7AI62lr_WvlEoMgk4cuYs0-zxsxHAY0	2026-05-18 14:57:21.843685+00
1ar57brf53e1lak5xzrntg88kc7xp2ry	eyJjYXJ0Ijp7IjMiOnsicXVhbnRpdHkiOjEsInByaWNlIjoiNDYwMC4wMCJ9fX0:1wJuja:j7rkF-u4nBdBrNMcNPJcq_Z2DePEIGY4GuhzNSXcyCQ	2026-05-18 14:57:22.036583+00
66czmttkrof13k03zd21uj6jd3gelu3n	eyJjYXJ0Ijp7fX0:1wJuja:v5eRAobk04wkC4XW1IFe-P2UdxNaw8RqrhI6aUPD-fY	2026-05-18 14:57:22.777899+00
9jtyf7m6kh63hu8hfac42frcu6bf2i0p	eyJjYXJ0Ijp7fX0:1wJujb:Bz_2wxkz-RZufXU4-KelxuIe9LjDS6i-34UR2fKb7Uo	2026-05-18 14:57:23.299999+00
5qhgbvutxmr46uepfuv1eh6dti2dwr5q	eyJjYXJ0Ijp7fX0:1wJujb:Bz_2wxkz-RZufXU4-KelxuIe9LjDS6i-34UR2fKb7Uo	2026-05-18 14:57:23.674691+00
tpbll68kmbpdnsnutdh0g3ioz5s6jvgf	eyJjYXJ0Ijp7fX0:1wJujc:TYzuLXM91Jw2PA3lqDI6z3fnVbtKo6kv5v0dZcCJEs8	2026-05-18 14:57:24.257564+00
rlankmszdc14gzra4uko6lu7yxhj8gof	eyJjYXJ0Ijp7fX0:1wJukI:yebLp_WxwgChuHLXF8NHigCwLWOUuMXTOhlHwLOtjr0	2026-05-18 14:58:06.086583+00
xlw2oag1ofnf4msnpyxuhk59lsmkek04	eyJjYXJ0Ijp7fX0:1wJukK:jW0D1rjr24Ff3-YI_60aMMHNmK-f-wybd0QythLo95w	2026-05-18 14:58:08.29082+00
38hpb4k70gpbqxs9yfa7568htbuuccgh	eyJjYXJ0Ijp7IjYiOnsicXVhbnRpdHkiOjEsInByaWNlIjoiNjAwLjAwIn19fQ:1wJuki:ocsKNCfE6xPMiyLQ7AY97wPdKj_JPwEJaakyiHRzKws	2026-05-18 14:58:32.248435+00
ng9myhv2hvsysn5bzqf2iuepeqz3gflk	eyJjYXJ0Ijp7fX0:1wJuki:yZvxwZtPmUWl8Xdv37Mk3H1GVCBbkpIL8jm5N9fUUnY	2026-05-18 14:58:32.754353+00
ffvjxp67jpdzeyhav9ja5ybq3q4j7ku1	eyJjYXJ0Ijp7fX0:1wJulp:4L8YzD8mILSI-tkBlfIC7vsmyFwSXUx7JYFgN53QniI	2026-05-18 14:59:41.740926+00
xxma5hv8gbeizzhn2e3m289nzmdh3u0n	eyJjYXJ0Ijp7fX0:1wJulu:JpDpvrBfgfOqeqZuYXQKwiaqsdxWWqh7RvcaR4Cvu74	2026-05-18 14:59:46.0077+00
6yyzaaxaiep2oe6k527aulrqb5vk5i0i	eyJjYXJ0Ijp7fX0:1wJumq:wCpI4K5UY88RCnDD5TCaWNQX_2JYtEcl2CePV9WLd5w	2026-05-18 15:00:44.552317+00
2yrn16qllqgf7ysa7f1rmng6xa5b68e1	eyJjYXJ0Ijp7fX0:1wJuo1:IzJ1KWDR-YZcLWDgACD27yci28jG-A8SHX3ccQopUkI	2026-05-18 15:01:57.583971+00
n1lmc0avfmt6xm348grd5bb6u7ewcucn	eyJjYXJ0Ijp7fX0:1wJuoG:3UNewwj9tsHHU2G9OodMkmBbTgX23-iW374uWxwX2Kg	2026-05-18 15:02:12.288365+00
ogpvoxwowzibivi4nsab7fow5nqqtkq5	eyJjYXJ0Ijp7fX0:1wJuou:CJBM-vxN2fXxnwqt57UOzU3DNQdTJuI5tDb3WhD-qR8	2026-05-18 15:02:52.48062+00
cko18ydposgazgsbww5qg5nss24izyig	eyJjYXJ0Ijp7IjciOnsicXVhbnRpdHkiOjEsInByaWNlIjoiMzc2Ny4wMCJ9fX0:1wJuox:0b1oIXdGyFItAs9HpPuOOv-sRWNhcB1UEsdF15Kywao	2026-05-18 15:02:55.97489+00
2u3sj76ibzbnvopou7n217ypugg0zazx	eyJjYXJ0Ijp7fX0:1wJuoy:dNX5kqL4m-6NHFVwIhTP9xiUf0GBE3Q90zyACqY4k0c	2026-05-18 15:02:56.649527+00
lxca2jkr5xhum8h3adp5xjappx6dxa2y	eyJjYXJ0Ijp7fX0:1wJupF:-k52uSsEigfdpnvbrihP71RmJT_4hEX5COb3dFHKCTQ	2026-05-18 15:03:13.181548+00
u78zuljqag1l69kxo8ke7i80xt2adosc	eyJjYXJ0Ijp7fX0:1wJury:IpIsphVN_d3Jendd00mWZEbLZC8QGtaJNfOBxDpU4VI	2026-05-18 15:06:02.080536+00
yhlx9kvbbrz68qqkdi9sw8na2vgnhc6d	eyJjYXJ0Ijp7IjEzIjp7InF1YW50aXR5IjoxLCJwcmljZSI6IjEwMDAwLjAwIn19fQ:1wJuuY:n5EhV-81FTLWRGHyU9VKH0YsD9cmMiSqkM3kqSJG9f4	2026-05-18 15:08:42.715217+00
pv0bsctz9khzvu31x1pnz3gx4nhn5es6	eyJjYXJ0Ijp7fX0:1wJuua:bm2BWXSpRcm6Gt_jPYeWHvWlR8owbKjbSKVXEqxazm8	2026-05-18 15:08:44.107257+00
4r0v9k39zb61v6b18vumgwg9cvyh2wjf	eyJjYXJ0Ijp7IjIwIjp7InF1YW50aXR5IjoxLCJwcmljZSI6IjI1NjUuMDAifX19:1wJv26:4BZbSmJVXD3RTGYt4HjUxSU1JIeqtxP0o2DF_0k8usA	2026-05-18 15:16:30.088775+00
lfyoz0hafi1wlqs9usouviddnamat8da	eyJjYXJ0Ijp7fX0:1wJv26:IYOSEl__-f2ORyGZ4zpYEf6-Uj5Xh-MlVVYHZgC7bOk	2026-05-18 15:16:30.626725+00
eqd7r6j4rui35ndxehn72eng0a6smv99	eyJjYXJ0Ijp7IjE1Ijp7InF1YW50aXR5IjoxLCJwcmljZSI6IjMwMDAuMDAifX19:1wJvAt:Cc1fOSCKpZHI16tqFrZ882Rn9ILx-NEONImbbwSsgc8	2026-05-18 15:25:35.267781+00
nylmy1ecfofos0vha73o7efxv0jubrcw	eyJjYXJ0Ijp7fX0:1wJvAt:eTqTjjBAlSqz4AIf-pZnPVFR8869xWYk3dq12r8zsAI	2026-05-18 15:25:35.804607+00
cj7ybnz5n8yw493wta15bgf400ts07dp	eyJjYXJ0Ijp7IjE0Ijp7InF1YW50aXR5IjoxLCJwcmljZSI6IjgwMDAuMDAifX19:1wJvBN:KGdjTj9mJ9b0CCZn2_XLILVvE8MU7ocIJdP2x8X6c5Q	2026-05-18 15:26:05.480868+00
poejs74hqzhyns345mci6t78m0ntr66c	eyJjYXJ0Ijp7fX0:1wJvBO:9ul6tiJ9FUXeOhedJGzB1Tgen314KA1ldZLfwS9hbBs	2026-05-18 15:26:06.002204+00
vxl075x60pg2o7o4thoo93l5nscip3zp	eyJjYXJ0Ijp7fX0:1wJvEM:nOOupCoVYEaKXT6hY_M4IFf_pSx2Y0qy_p5MPluOgoo	2026-05-18 15:29:10.989786+00
49ei5zy8uae7pyc7oycnzdbgqhv62u1j	eyJjYXJ0Ijp7fX0:1wJvF0:zEtSy-8Gw-6_a_Jt-qo3u0tXla_g5x6LzA_NFo-_IdU	2026-05-18 15:29:50.498289+00
unte0ooyi8s8qi5c8cmimot36lhe78nr	eyJjYXJ0Ijp7fX0:1wJvHW:yRaNguRv2U00XMq083psJYYUcaB3bp8aTCOwq_BtriM	2026-05-18 15:32:26.632638+00
113l78scf6ruelduvwje4ouhy6tsbtyi	eyJjYXJ0Ijp7IjIwIjp7InF1YW50aXR5IjoxLCJwcmljZSI6IjI1NjUuMDAifX19:1wJvJn:5sAAynNCB5t95q3H9MTX6UJr7jqZhG6qBhkzBoiXKYo	2026-05-18 15:34:47.526836+00
e9en62neozv4pq80o38sdc0kzrzshbrp	eyJjYXJ0Ijp7fX0:1wJvJo:VuATOrlBQtGXV2_fUe2k-M2fxI7vAJW36lJ0ZulvA6s	2026-05-18 15:34:48.242359+00
dlfipzdhd4ahgapg6xjxr34b3oy964az	eyJjYXJ0Ijp7fX0:1wJvXp:X8zS4t3-T4maDjuFPiSNp1ar1gUhLCNkoU0B9W0_hi8	2026-05-18 15:49:17.477774+00
6w652xwqz6afwf2p1atswe7eawsnfe4p	eyJjYXJ0Ijp7IjciOnsicXVhbnRpdHkiOjEsInByaWNlIjoiMzc2Ny4wMCJ9fX0:1wJw2J:JfLehRw-9Fyz-AddtAw255bG3cy4j-2tHm56iETG-Dw	2026-05-18 16:20:47.590955+00
sx7gkuw7o1ad4uajmr9ajdywd71lx7mt	eyJjYXJ0Ijp7fX0:1wJw2K:YNdmKZRHhSUhRvsaNsaxGCe6D-ZYYndDdsHJxrfIvr8	2026-05-18 16:20:48.406802+00
a3wau6f1i2ceuxw4iij4k239z6z986ns	eyJjYXJ0Ijp7IjciOnsicXVhbnRpdHkiOjEsInByaWNlIjoiMzc2Ny4wMCJ9fX0:1wJwBT:Dcpd6ZA0Uw-Z7r9hXGPHjRETEwHDmy7Nv089N95C1Fc	2026-05-18 16:30:15.593566+00
tyc4q8p4m9gy2vihsjob29p71206wnv5	eyJjYXJ0Ijp7fX0:1wJwBU:WNi_0YuiMfvpjEsIObPGFgpHr2AtDFZaaJz4ZfBZNNc	2026-05-18 16:30:16.188946+00
wolfzcuha97uepb96bm03js9bffnjm26	eyJjYXJ0Ijp7fX0:1wK8dZ:ObXE0GdncH_MIfmnvZFaz4T6CJjBPledB7taD-Ovo7U	2026-05-19 05:48:05.1867+00
g4l021hwrgl073aavxa62z3884i0jnme	.eJxVjjsOwyAQRO9CHSHD2nxcps8ZrGWB4CSCyJ_K8t2DIzdu38w8zcYIp4X1235jA65LGtY5TMPoWc8MuzCH9A75CPwL87NwKnmZRsePCj_TmT-KD5_72b0IEs6prlEG4QR6iCYaJQN0CoS0NnTaGwLtKkZsrTVaQaOxxWgapFaDjORBVSmV9Vvy_6XYf4gcP6U:1wK7OV:tESVMXgSal5sf2BJgrl_L00kHYc1L0P81v1qEYySuN8	2026-05-19 04:28:27.189796+00
u1zvwlmxi5zjyux6dlcamwaiw6gthn5x	eyJjYXJ0Ijp7fX0:1wK8dt:Kx8DtmvCAm1272ixpoCZvzqy8kpsxOy3wGUMZhk0GHk	2026-05-19 05:48:25.993298+00
g8j1gl7pionkkbjzs1mk9l9jxxt0ile0	eyJjYXJ0Ijp7fX0:1wK9BZ:ua42sTzZFr_SKKFXxBtrE7Z9su0oLdI8YH-ggfb5wis	2026-05-19 06:23:13.999453+00
9g6lral3nvrnq0ctufj6un9accgfyayw	eyJjYXJ0Ijp7fX0:1wK8bW:xeUahcFqeGUo6jvMY-wcDwkhqZTIVxDQ_siz09LnVAU	2026-05-19 05:45:58.595342+00
fssrauqhzcqrvcmuti489w0udze2zj4m	eyJjYXJ0Ijp7fX0:1wK8bW:xeUahcFqeGUo6jvMY-wcDwkhqZTIVxDQ_siz09LnVAU	2026-05-19 05:45:58.848191+00
llz55mr3wt6az3b8b2rm6ffi2rqfiwdd	eyJjYXJ0Ijp7fX0:1wK8bf:c4An7R1zS6Fxq3yeiX6Uk1USeSywrw-1g3Fazr9ulRI	2026-05-19 05:46:07.287699+00
0hcu2szke5g64h5tdbq7jcczo4blzpfw	eyJjYXJ0Ijp7fX0:1wK8bm:DEy-eXSlU78PDT1mMAuYHDhARbO5l-6oiXNnRBTF9EI	2026-05-19 05:46:14.589642+00
9bjqtp5rb2tqzjmao4udf9633e9jtyk8	eyJjYXJ0Ijp7fX0:1wK8cF:z48cLnbJGp3FFcH5qqycQOfV4GXg_5OVrNejWWey4f4	2026-05-19 05:46:43.50302+00
n73iexnm0q3g9fotzm8q6sckmysxbu55	eyJjYXJ0Ijp7fX0:1wK8eI:4uEw0duOO9nID1oHOTeAsME1JZ_hHFy5dm5kFVXwDPg	2026-05-19 05:48:50.400151+00
4o62ghpd2j01ifzcyniy2i2yi5je81ij	eyJjYXJ0Ijp7fX0:1wK8cG:3YRouQ2-q879pWEAEthSnAcaZhnjKCUgA0UObevC-zE	2026-05-19 05:46:44.488524+00
7asuj5xylmyqer1rgwgj4xjc6b18q2p3	eyJjYXJ0Ijp7fX0:1wK8ca:bxR-oxCwCevQVqIY9RNV2RPzgXWaMAGGbDnoEyQlGmU	2026-05-19 05:47:04.030998+00
npcz3tzepobp9b4rlw56ac1q7ibit2cn	eyJjYXJ0Ijp7fX0:1wK8cl:KYiRYLGKQASnmJYe7GKXJXUc7jVxKUbEAL0M0HG4xqQ	2026-05-19 05:47:15.543022+00
80qwqeqnox2o71uy201vmor970inv9s6	eyJjYXJ0Ijp7fX0:1wK8cm:6Gbpoth6Ve_8-sD-g1pyuURYg6nBnvki3y9Joz1dFbE	2026-05-19 05:47:16.013805+00
355pl0s4ygcql959bf77rloldq5zzkw0	eyJjYXJ0Ijp7fX0:1wK8cs:gpbm8Bcu53JOjkgpLTOG5agaPa-3x-RsBY1eBrjodyA	2026-05-19 05:47:22.717109+00
vuuay832cqe4agxthkrbx3qazb84ohg2	eyJjYXJ0Ijp7fX0:1wK8cw:rpBhMidxJSUDy9NoppSFGN9A3O3v_U3HfHzIJcdxkqE	2026-05-19 05:47:26.895963+00
d2a6d7h43ulqst2c0cn2nmwbku5tqa8z	eyJjYXJ0Ijp7fX0:1wK8cx:loEsWjvHZHRj0s12nAtY3jexmlqYo-NvW6wuH9nifxc	2026-05-19 05:47:27.256167+00
ewnj2s6a9dvbxp0kn21vpizhbyxaki6p	eyJjYXJ0Ijp7fX0:1wK8di:HAYIA6cmMHfqiZqgJrKUCsafmO2Ic2yQ0QiZKXDF1_g	2026-05-19 05:48:14.181312+00
jb7ewzs51n3at23j4iow9hqkej1ixbyg	eyJjYXJ0Ijp7fX0:1wK8eG:Fl5pTiFe3l5-WSVLeX2bul3_rC8snI_Xf5amxrMYFls	2026-05-19 05:48:48.374621+00
38j49lxgxhqy05r4dicogub0ef1kk15w	eyJjYXJ0Ijp7fX0:1wK9Cg:eBsI9MliMcHEsQ-7CUd3KVqWfzGCaLmXcfum7obT5YA	2026-05-19 06:24:22.74878+00
lb82y9c5rqhnaursqgu3u2bf0r6njw1f	eyJjYXJ0Ijp7fX0:1wK9Dy:FZW89YLO49RmjhjOI6NysR__3zpJXp5Nws8zMrAKzoE	2026-05-19 06:25:42.184358+00
fxwkq2xu60xgwk7roo4z1rjvg97e0t7v	eyJjYXJ0Ijp7fX0:1wK9Hq:I6vkVUAhK2MB3Z2fh3UptotOM1gfgbGbfOSV30fpyg4	2026-05-19 06:29:42.79587+00
3xwtypor2oet3pqevev0mno5w7phr2xx	eyJjYXJ0Ijp7fX0:1wK9Qe:cclVcxDh9H8hcFk6T4OkBsOXXGze9F98_JBjgvcZkCY	2026-05-19 06:38:48.483536+00
w652uyqdalyav64zzbxc5xuwg6efmaht	eyJjYXJ0Ijp7fX0:1wK9Rm:SyxzfWm5V45VUZIPvPWv1guHwdgxO82xttl2SwJH0kk	2026-05-19 06:39:58.09898+00
w3zqw5xbrqpufvburh3x1aigm663nr78	eyJjYXJ0Ijp7fX0:1wK9Rm:SyxzfWm5V45VUZIPvPWv1guHwdgxO82xttl2SwJH0kk	2026-05-19 06:39:58.293436+00
ysxc3eiz27kpmmreqx9mh37nrmfsm1n9	eyJjYXJ0Ijp7IjEzIjp7InF1YW50aXR5IjoxLCJwcmljZSI6IjEwMDAwLjAwIn19fQ:1wK9Rm:eU7GZG8bespvcCoZ2dvCGzCyGW4f340Kcooo7RTPIF4	2026-05-19 06:39:58.395866+00
4818mqb0h0rtkam56yozb7fmgvbr6fr5	eyJjYXJ0Ijp7fX0:1wK9Rm:SyxzfWm5V45VUZIPvPWv1guHwdgxO82xttl2SwJH0kk	2026-05-19 06:39:58.592753+00
qin32cddxaicfebgt3admhlqrqlk86x4	eyJjYXJ0Ijp7fX0:1wK9Rm:SyxzfWm5V45VUZIPvPWv1guHwdgxO82xttl2SwJH0kk	2026-05-19 06:39:58.787889+00
ff5p9c6tedbue9z1mrsiuzc0ffvfbp4h	eyJjYXJ0Ijp7IjE5Ijp7InF1YW50aXR5IjoxLCJwcmljZSI6IjUwMC4wMCJ9fX0:1wK9Rm:pKRSbG_HVFW5PLbLHygfkDoJdOBNPVitnVydIosuj00	2026-05-19 06:39:58.891853+00
jwkvpzarfo96rfr65xhgqzq8jn8sdxa2	eyJjYXJ0Ijp7fX0:1wK9Rn:JM8Amj3Am40-P5n3en8BvrHweGto1S3768rDhbfmdw0	2026-05-19 06:39:59.092214+00
5sfnn4nhmocftd2j1mbdjzd1hdoa4hwz	eyJjYXJ0Ijp7fX0:1wK9Rn:JM8Amj3Am40-P5n3en8BvrHweGto1S3768rDhbfmdw0	2026-05-19 06:39:59.285993+00
6ayvxgfxx9r4uobf2v64k0ridb0h08qs	.eJx9z8EKgCAQBNB_mbPEbqGifxPSwUuU2CHEf4-g9LRe9vSYmS0Ia8rwBezee17rnmO-4VnhSDFs8NBEExGqwiyapRkjGtMMLyJiosasXGeN_bP0aFRbPmjs_zGJau6IReQ-VOsDZCtheQ:1wK8eL:_1tmA6gLhb1VlY6WzkOoIEk9a0M4YWSoVcFBjdhvEY0	2026-05-19 05:48:53.690627+00
wz4yty4pxpyvrml05pzbo2bcaj4efc3r	eyJjYXJ0Ijp7fX0:1wK8eS:pxwQPl1kXBZxMs2AKDlj-57aK8ThgCIhzFmml3IFUDQ	2026-05-19 05:49:00.1899+00
wwm2dhk4i77u12xwxphmax1bst6gyt0s	eyJjYXJ0Ijp7fX0:1wK9Rn:JM8Amj3Am40-P5n3en8BvrHweGto1S3768rDhbfmdw0	2026-05-19 06:39:59.386006+00
9z87dzbctfuqxpstl2ae3jdjjct7xivb	eyJjYXJ0Ijp7fX0:1wK8fH:PPVCCP4RL27mqWfcFsJ0yhwBsQEjejeDdPVvWbGdge0	2026-05-19 05:49:51.773214+00
je4rgxj7ka9sy5id0rqyh80yvqn0wlhz	eyJjYXJ0Ijp7fX0:1wK8hO:eQdaqpwQ0RVxX9Ieb17KC52LkRN-5aa_cBkPlH7ZgWs	2026-05-19 05:52:02.449552+00
j9ihbxzdm9gy2vr6ydja16il7vcb2vx8	.eJyrVkpOLCpRsqpWMrQEkYWliXklmSWVSlaGOkoFRZnJqUpWSqYGBnoGBkq1OkpGONUYw9WY4VRjBldjaIrPILgqY5yqDA1gymprAc_2N9Y:1wK8dI:EHBVB9QRKpOAPT9tASYVnANT-KwDL-94lkI7q7z7tPI	2026-05-19 05:47:48.667115+00
b8t5hv8e5zjr4r5pe2lvz0mxhiyfbzwa	eyJjYXJ0Ijp7fX0:1wK8hO:eQdaqpwQ0RVxX9Ieb17KC52LkRN-5aa_cBkPlH7ZgWs	2026-05-19 05:52:02.865014+00
7rde5glnre969mt2vhkgkaspf9yaiz71	eyJjYXJ0Ijp7fX0:1wKavE:NNJEVYhgPWFyGNzQYf8ZV0DM9sNCnQJ5r3WZoA1ewrU	2026-05-20 12:00:12.382184+00
50nqkmhzeuf3usybe35hswx6lys9t5pj	eyJjYXJ0Ijp7fX0:1wK8qp:RiRUusa3hBaFUuERf-T6Gb8ec9Jq8Xt8SREHWBg5Ofo	2026-05-19 06:01:47.48237+00
cz046se48vtqnde22v7jp7opk706ep1t	eyJjYXJ0Ijp7fX0:1wK9Rn:JM8Amj3Am40-P5n3en8BvrHweGto1S3768rDhbfmdw0	2026-05-19 06:39:59.587614+00
8clm8bio4rv5lc3f92fqdm40e6xq2zmh	eyJjYXJ0Ijp7fX0:1wK9Rn:JM8Amj3Am40-P5n3en8BvrHweGto1S3768rDhbfmdw0	2026-05-19 06:39:59.70063+00
r1urvrin75vfz3wlcs3g7goduck91n4c	eyJjYXJ0Ijp7fX0:1wK9Ro:1-m3jyLsD8kBTwy8ibo-9VSJyMgiRVYtDFxHafInYgA	2026-05-19 06:40:00.085039+00
n9543pq9rsz40a7wtdsof9khu3fuu64a	eyJjYXJ0Ijp7fX0:1wK9Vw:Jl35KsbdgFMzJ19iA5547_FyREF_EH7DdkBLzDi_jrQ	2026-05-19 06:44:16.09832+00
xuiorici4dnl3s5ezyotel419mfz2mro	eyJjYXJ0Ijp7fX0:1wK9Vw:Jl35KsbdgFMzJ19iA5547_FyREF_EH7DdkBLzDi_jrQ	2026-05-19 06:44:16.488212+00
paxv5fz43ix6adfesv1viv1o0lu0rkqt	.eJxVjDsOgzAQBe-ydWR5wcaGMj1nQLv-BJIIS7apEHdPkGho38y8HRzlCsN-PGCirc7TVkKeFg8DoITbyOQ-YT2Jf9P6SsKlteaFxamIixYxJh--z8u9HcxU5n9tTdfYlhVqljqyQ8agmKlDTb5naTlK05HuWxsaREIrtVZKmRBNjNLB8QNDVTsP:1wK8vx:jHz83KVyx0CMHYwfoPQsMmgg6zHPPtUmxhF24NRxPpI	2026-05-19 06:07:05.000382+00
bjcny1benatxda5fxlt86lne330e200c	eyJjYXJ0Ijp7fX0:1wK8zX:JrML0lo4PB-Il2B1dyW3QEv_Fu4iTU-q2wAWj3GFYIQ	2026-05-19 06:10:47.834114+00
8006v2ex32oi67uo4d6h7s9rjelid17p	eyJjYXJ0Ijp7fX0:1wK933:6Ldt3th5mZs3xptF2fGmXQU1Z5JtadRHBpBuCeYKih0	2026-05-19 06:14:25.447073+00
05gsegl51nu6siiyon009pu3c2if52k7	eyJjYXJ0Ijp7fX0:1wK93z:czzw06I7Sod0hWoCZ6eE2YvdOAMSVyH_aPCGLow8o-A	2026-05-19 06:15:23.08173+00
99fd1j29ddydm6a0sgymd1r8sp5w1k01	eyJjYXJ0Ijp7fX0:1wK954:UhUT22rxxHhV9YiCr-ajhOaqQFr788xmYVv9sLr2I2g	2026-05-19 06:16:30.546813+00
e30njg7kj2yb0oxq6k57bzbx9jacd0m8	eyJjYXJ0Ijp7fX0:1wK96w:8p4Ynq7lao9f-KdZme5jcAfGubblke3nIYA-tSSFgs0	2026-05-19 06:18:26.292757+00
aw45h62260m75u578pnb8mr47378m128	eyJjYXJ0Ijp7fX0:1wK97r:ifMEc2op7TX3TRpY5edRoNkkcjQAUdom-Z1zzYJqUaw	2026-05-19 06:19:23.990935+00
ky8npr6kaqos4u37ijrtey1a8ml695ix	eyJjYXJ0Ijp7fX0:1wK98i:kWXzlyfSmpbrpma3yVOXSEpzwCwYnOyx8eGudFYvPmc	2026-05-19 06:20:16.792518+00
q8gfiycr4b1og2efm7atmw32p8vypts7	eyJjYXJ0Ijp7fX0:1wK99G:iPgDpiPgGUda1NHIQMCByD_SmfQC7hc8eFRaH70OAo0	2026-05-19 06:20:50.894801+00
wjdng49j4qh8fxtywx5tmnti9m52lqnf	eyJjYXJ0Ijp7fX0:1wK99M:ztH1_re1JWJU0NwbMf2RVK6U30R-dCTEuOEqAxrWpsk	2026-05-19 06:20:56.396118+00
r4x825jsi7afzkhd77ddsdwo6ontwnum	eyJjYXJ0Ijp7fX0:1wK9AK:4MHLR8tY_KtVvKRCVVu4rDB18goUUaMjqbfWAWUdXmg	2026-05-19 06:21:56.195374+00
0a9ryrljcgqjqht7rein4hgufjwzzc4g	eyJjYXJ0Ijp7fX0:1wK9AO:kto_-49zwDb3Iar3-ASm8WCvmQh7HmKy2o89oqmbwgE	2026-05-19 06:22:00.191499+00
mhxu0jkid319s6r2nxaramxpbsrb1vjb	eyJjYXJ0Ijp7fX0:1wK9Af:EbpoUM3OM1H9AZY2VxoBQ7QVJapHsaVlpJT9hu4qsas	2026-05-19 06:22:17.292901+00
bs5nje717v1r4zkw6zn3paoe6q8mkk7x	.eJyNkrEKwzAMRP9Fcyi2Ysux_yaEDllKG9yhBP97CcRWljNZND3upDvttMxbprQTH-PznV95zT9KdqD3ti5PSjQa8zCGykAWMs5XxkGG2Z-M73lVoRGbSYMCVgoSTkggpEITZKxvUOzd30LqSOl1FmcZFcIZHFINu5Wnxc1MSjHeS4JqGdyyQrgcdjFWCrfD4qWuhd-TLyfigrQf7uzupb6ovWXInYKqYyl_ak_ztw:1wK9Ao:z6jMGJtiTFEJtA26do27rVmd04uUAZLjn-55FVoJtdU	2026-05-19 06:22:26.511112+00
9m3jruc2tw9u0ys8d4tbldkjovol7dtt	eyJjYXJ0Ijp7fX0:1wKbN5:PFrZYYLk7WNXAqXeN5s7yDzhaYlAOS8RgcVLLIh_ZbU	2026-05-20 12:28:59.782753+00
u5f9btpt22i5dvt32nbl69mdq39kuhng	.eJx9z8EKgCAQBNB_mbPEqrmSfyPRoUuU2CHEf48I7bRd9vSYmS2YY8oIBfyc44xbXvOFoBX2tM4LAphoIEJV0JOIXEdGNLYbLxvPvrVZUWmib5T7K-xK_s-w46ZENLo3qdYb0HFXBQ:1wK9W3:ZlnxAfRm9hdNMzQHv6GShc7OdZDnUQkWSBF8LWGnaRw	2026-05-19 06:44:23.093527+00
afkpopqn2ofpnfdg615du866u6ufqn1k	eyJjYXJ0Ijp7fX0:1wK9W4:YkGJOQNSaGQQ0ivGYXndruWacJ0p5TcOd4TrRWVe6DE	2026-05-19 06:44:24.24098+00
zfhcno6jaknow41j8e7dts6p9bc0q4jj	eyJjYXJ0Ijp7fX0:1wK9bu:GeaBxrvwkEhMjXos_fxSxOf2Qg-n1mh5W-DMlhogVE4	2026-05-19 06:50:26.988785+00
oqw80odh1jx8owr4aytmhqdvrub2yc3p	eyJjYXJ0Ijp7fX0:1wK9lg:cf_Z8E4_F56uwfXThGS_Xa9E1wb9pXt8kmmFnJkMPJg	2026-05-19 07:00:32.792389+00
ww895sbcsnxjablwzmr03ljuf0ja97xi	eyJjYXJ0Ijp7fX0:1wK9oE:2Pw4E5VhI5ZIThxhEYJggIQ_yFe6MEDSpKuwPqjfZoo	2026-05-19 07:03:10.392698+00
pxkv7otk1zo3ewic6znmjjgm6nmt43zf	eyJjYXJ0Ijp7fX0:1wK9ve:ezSjJVPqOd77xxfJZ81-rFWfSKILJtt-TERLePD4Wz8	2026-05-19 07:10:50.140996+00
8a74h5snbduf9qz6ekbaouz6oaz3jo38	eyJjYXJ0Ijp7fX0:1wK9ve:ezSjJVPqOd77xxfJZ81-rFWfSKILJtt-TERLePD4Wz8	2026-05-19 07:10:50.38267+00
8ppmza21f2jwz91vtfd7mjyayk4whur8	eyJjYXJ0Ijp7fX0:1wK9wg:cbEUrvVXr3n3GZmXnyFpRDYfiNzOVDGKh_KmpO7Pimw	2026-05-19 07:11:54.985835+00
iqwuc4b2ke9s0vp3681efeqkscjr2jsq	eyJjYXJ0Ijp7fX0:1wK9wm:LBT6eso2GYlmH3I3kTF5dEV2FJYpjSWjdEGSS0zBqSs	2026-05-19 07:12:00.81776+00
vqi9k3r3x0o5mzqng0p09a82d8hfldx1	eyJjYXJ0Ijp7fX0:1wK9xE:Ee2vtCRhRPYKiP3YIqYlhPxuCimB1Keady6FMxaeOLw	2026-05-19 07:12:28.408624+00
gr07auvqk035vss4fmk37fhyfs2o6f3q	eyJjYXJ0Ijp7fX0:1wKAM1:12mdU-GXYVmfpq6eAReOboB5B82ONSNzPYJIcp-8wJQ	2026-05-19 07:38:05.29864+00
vw5onlhd7nnfwglswb613nj14omcuidd	eyJjYXJ0Ijp7fX0:1wKANY:Ip-t1_EksnXigsiI4ZzKOrt8muXvDNIxTmQuDRJKlLQ	2026-05-19 07:39:40.81372+00
1bgcrua06uw9s6rw77gyong50imt5ysw	eyJjYXJ0Ijp7fX0:1wKANa:0WQr4dI_WFUejaBeoazSVZjMqX3J8BRNAvPvFN-xrA8	2026-05-19 07:39:42.996336+00
is1ixb773hi1bsi9spxartcid3vadufh	eyJjYXJ0Ijp7fX0:1wKANq:9M_2vlf5wKTnWkAkNbSr8pM1GRquwRDMv1GLfQKW6ow	2026-05-19 07:39:58.921901+00
b9vpeh4rkvijgaeovhyhdwxmywffoui6	eyJjYXJ0Ijp7fX0:1wKAPO:X9npUQ5J_raBFPQs8Xka6x8OqkGz70-00awWwAV59eg	2026-05-19 07:41:34.194047+00
eh660tv6605xl33ezgjxw7q4i8hcpoeo	eyJjYXJ0Ijp7fX0:1wKAdf:4pjnHw-tv0CDPQyD7zcb9B-Y8o80_xADeHl6pSoZ8NE	2026-05-19 07:56:19.219323+00
svqjbh4g4itt4o8hgrn1ph05jfv7f38x	eyJjYXJ0Ijp7fX0:1wKAdf:4pjnHw-tv0CDPQyD7zcb9B-Y8o80_xADeHl6pSoZ8NE	2026-05-19 07:56:19.388967+00
bnrvn2jz8ye2xl73enfo7s90syv3jp5j	eyJjYXJ0Ijp7fX0:1wKAdh:XT77Ww1f12i7fy-l2dAkZj8OXG_Ngj3HHKN5pwcVoUc	2026-05-19 07:56:21.062597+00
rgkify5ypuipy01ip0smteukrvjwjnvz	eyJjYXJ0Ijp7fX0:1wKAwU:-DJq0gts4DGrOa0LoiCeYGCgCj5BkXLJU6w0CTLkpHA	2026-05-19 08:15:46.685354+00
rr6p7gbw61iioqcyy1u12pvt845p3msk	eyJjYXJ0Ijp7fX0:1wKAwa:W49akSi9QoA0WmDD7tHD4L5yuVSwyJ8NssIfnmR_Cv8	2026-05-19 08:15:52.225645+00
f6dfnkiir1dnqt7q4oqr6pfqlvt1uqza	eyJjYXJ0Ijp7fX0:1wKB8o:sS3epSmhBcfqTqEROY_Ui4-ss8r9dy8TDIo9CNm0NQ4	2026-05-19 08:28:30.670667+00
xw99n1n82fafbv356qlbw6msa4js12nv	eyJjYXJ0Ijp7fX0:1wKBQ4:MA2vHd8KgQ6GshS_3V7-qVe0NG-AFytOH8nTasWHzDE	2026-05-19 08:46:20.61626+00
39zeaklplqk0kxl3s0iwt5abvlydtzj5	eyJjYXJ0Ijp7fX0:1wKBQ4:MA2vHd8KgQ6GshS_3V7-qVe0NG-AFytOH8nTasWHzDE	2026-05-19 08:46:20.999825+00
va8tcwv2t1wykeyt8zanm3bycz2amfds	eyJjYXJ0Ijp7fX0:1wKBQ6:1SQAkImsjO9YR1IXMbNtxOsbYKQ6_oHd2Vs_iegDcsE	2026-05-19 08:46:22.287695+00
9xf1t6yjxmak8nxe9hxtmjg9q4jycpjt	eyJjYXJ0Ijp7fX0:1wKBTD:WVLc8atyRSuk-8nU9rVbgp2ozXSPW1tSlWbnnshsutM	2026-05-19 08:49:35.120908+00
yzc8cojtnvt0mg09amkk2n3le33kgzok	eyJjYXJ0Ijp7fX0:1wKBVX:Wq67K-eYq981eUuXDMYBu_K-erhMzc4Qv68a1my3_-k	2026-05-19 08:51:59.594417+00
1fbsndltybjuy0k0ghyogpldcci51p8y	eyJjYXJ0Ijp7fX0:1wKBmK:iTJJbMKMl5WTzYvvaxE9x8oNnmbF5lLArvnxt44iJV8	2026-05-19 09:09:20.394521+00
fs76hymta4k6g21fw4xpnmvbl3gqsikz	eyJjYXJ0Ijp7fX0:1wKBpP:AQ8g1LUVLMEul-xq00Zs9-9tstFhn9mGBZFl22tlcjg	2026-05-19 09:12:31.491889+00
c5sdn8imh5cdaxsqqov1hzoc7vvv4w7k	eyJjYXJ0Ijp7fX0:1wKCSs:4BiXpl9CKjsEGclutIW8Z-9wfGsH5lc5rqzkStvZwZ4	2026-05-19 09:53:18.301805+00
h4rkjnge2g1u2s0n103wfockbew8krdk	eyJjYXJ0Ijp7fX0:1wKCez:ItOyFixQmK_grZNJBnRdGju6PXgbmdMdpEcJfxBHb1I	2026-05-19 10:05:49.435434+00
gryb5nw5zcwb3gml1lncwe1ubrv6k3d5	eyJjYXJ0Ijp7fX0:1wKCfC:omCwVv9Cft0gJIWOy40eyBXo0CrodkhFXz4lcd0sXbU	2026-05-19 10:06:02.79248+00
m44ua3s8he35klws4hbf42y0feqac7dr	eyJjYXJ0Ijp7fX0:1wKDU5:VdThNuDbOl8xNw0dRZ7fcDr5VNr-y7QBRoMw4aNOUa4	2026-05-19 10:58:37.726592+00
7f2iox42c8223s4cs804zwg89mpk1fr0	eyJjYXJ0Ijp7fX0:1wKDWK:bndAxn-MK6xFw4wzEi0v8Nrvxmvp4T5exBrp7jZBuaU	2026-05-19 11:00:56.681582+00
qr54rxv06nw5vxhc54ykq6y4r4g1y11o	eyJjYXJ0Ijp7fX0:1wKDWX:HV3LEo8CvJybOs1Vw9GTk6GoiSZCvxgrHd0OS2revVE	2026-05-19 11:01:09.186113+00
9yka81g4b1jq88m4on6n9v1gcsmee9xj	eyJjYXJ0Ijp7fX0:1wKDkV:BRIEYNrAcvE2SJRT3bkSUv-DAh-tEPx2YeAkxcTwzqg	2026-05-19 11:15:35.176116+00
ef4ewpxyjjqgofyaulk5tvqg01odcn6v	eyJjYXJ0Ijp7fX0:1wKDuS:apChLv9w2DtStsz7M696Y2Z_03gHQs6Mn4fK4MA2lF4	2026-05-19 11:25:52.382157+00
y9x0s9tk8nnqswzyrcomat1b8jwq721j	eyJjYXJ0Ijp7fX0:1wKDuS:apChLv9w2DtStsz7M696Y2Z_03gHQs6Mn4fK4MA2lF4	2026-05-19 11:25:52.782786+00
fnv8pli8g1683nif7qsyegusfvgs0xxg	eyJjYXJ0Ijp7fX0:1wKE88:CPaKfQoNX9EMFz5amqwL2ygHsq5NRKlabNmTqTUEbBE	2026-05-19 11:40:00.638719+00
7tewg2ogtomc19tbxer0s6zg4187xh49	eyJjYXJ0Ijp7fX0:1wKE8F:NCrpieSEbhELbEGJRUK6SmjTrl4ax3WdGSlOzNiQmig	2026-05-19 11:40:07.191867+00
810b2yhvret40l56d18lwac6d8ges1sz	eyJjYXJ0Ijp7fX0:1wKEK4:0WNq7mpgWXmzifNA3qRwhfnrmNcj-5vZKsSxclwP9vc	2026-05-19 11:52:20.310064+00
our7kg97haxod4369w2p7hp9dtfq8peq	eyJjYXJ0Ijp7fX0:1wKEsw:vj85a_4LTOM-YMRE-Y0yUKQkg4ArrFDFtoGXMp_5s2k	2026-05-19 12:28:22.53132+00
0wikt6421rwpjbx6swpewehxu2hnrndn	.eJyrVkpOLCpRsqpWMgcRhaWJeSWZJZVKVoY6SgVFmcmpSlZKxuZm5noGBkq1OkqGxjhVGRoAAUyZJU5lpghFprhtRBhlhE8RVI0ZTjVmUDW1tQCELUJD:1wKF0u:PeDjC6Yf3V2w13KtWHxw5BrjN-vwDgJfOVx1SHCz5lg	2026-05-19 12:36:36.043903+00
75vbhemt6zic71hj24oxqg4qh2vhdp8d	eyJjYXJ0Ijp7fX0:1wKF1g:Eey9LJVJjVhUEjHeyMI-C2EYRRUNrudYuSwdprmVD4I	2026-05-19 12:37:24.09321+00
hzhsa59fbtv942685833ynmh5mqbrh1h	eyJjYXJ0Ijp7fX0:1wKF8C:EXeRRg1BjLHf2tPeGjhaFbOiOjfIprDcgGtJkQeQOMw	2026-05-19 12:44:08.337193+00
cby2r8b3zsfxpxj3091ll3fhtjtfz2j9	eyJjYXJ0Ijp7fX0:1wKFGl:Q6rkcawbu6bEiVIfNSzcVc4vp7LoiNRty-amXBv9ESQ	2026-05-19 12:52:59.6265+00
75q3dh0sqawa0psuaqypwe5jql97er9j	eyJjYXJ0Ijp7fX0:1wKFMg:dAtCk6rf6xAwsOHvHG65rN1YoxzodRsiGd_uWD1rhwY	2026-05-19 12:59:06.870224+00
mrs5k8d11qe7571mw1plkr1t0g6ty10o	eyJjYXJ0Ijp7fX0:1wKFXF:F86kIn2hCg0_uahHdXYr7WGl_EoSLyuawRFnHpT1_UU	2026-05-19 13:10:01.718952+00
t5fgkz1pfosh5xseo4w0qiooizpgssa8	eyJjYXJ0Ijp7fX0:1wKFab:TGN55EnbKx35ykDQCd9f1QUNAJwMMJ3tzFe-DO7o07s	2026-05-19 13:13:29.361744+00
6f6cc5b5132vszyfjrdq6c0bbb3qjsu8	eyJjYXJ0Ijp7fX0:1wKGQn:8Kh4zH7d0KtmSYuIGk_wrvxUS2wdk_Ruu5TYPULA74g	2026-05-19 14:07:25.654405+00
re1gdm7id3favy6hdcib6muk8780v2im	eyJjYXJ0Ijp7fX0:1wKGQu:8cM0hCT7WqenJezPrZyy_7loYDouutPMIaXu4MqZhro	2026-05-19 14:07:32.771592+00
ndcg0o2a7duwvz5yga8exv3gz3f5vqcp	eyJjYXJ0Ijp7fX0:1wKGxe:CqKd_6ng_56pFCUaVCM5a-_kKDvo_SqUhTZ_dGpIRyk	2026-05-19 14:41:22.182347+00
h7xablkzow56yh5jbaq36zbqeme7te5l	eyJjYXJ0Ijp7fX0:1wKH0w:3JZYwpuiu2pioWgUc4kwXn7kPvcccHaVtKkXg-xvtTk	2026-05-19 14:44:46.481004+00
kitis3mtaam7sowm11hnumpade2sywap	eyJjYXJ0Ijp7fX0:1wKH2p:SEniz9CaGna5arliBRY36FfkFXl1ehGpi0qYeKZPNv0	2026-05-19 14:46:43.097441+00
w7za741646fswoq856g2qv376z7wgb9s	eyJjYXJ0Ijp7fX0:1wKHGW:W_B2L6r_EFxvDo01eCziOpk4KeQ17BQI1bTL5mW-4S0	2026-05-19 15:00:52.387546+00
w0u077uacrkglxca1zq89cc94ek55i99	eyJjYXJ0Ijp7fX0:1wKHGW:W_B2L6r_EFxvDo01eCziOpk4KeQ17BQI1bTL5mW-4S0	2026-05-19 15:00:52.583352+00
7lqpb1qgieuoyr8eltqv6vjvi5fslawl	eyJjYXJ0Ijp7fX0:1wKHGY:ppsk0Yd3Vil3UgVY919zIE_KkVK5OieXiFZuyTdhyCM	2026-05-19 15:00:54.263962+00
fmjxctfi1a5rfgmo2o1dlgnai791uiud	eyJjYXJ0Ijp7fX0:1wKHGY:ppsk0Yd3Vil3UgVY919zIE_KkVK5OieXiFZuyTdhyCM	2026-05-19 15:00:54.557362+00
s6w8evjkcbr3g5gqoemfehix3zrhmc7s	eyJjYXJ0Ijp7fX0:1wKHGZ:345yZOZCSyqyMYfzZao98pAo_Abt2-iwot-ZZol6R-w	2026-05-19 15:00:55.591824+00
apaptqyhfhc61ktpxo8yk2w7im24wg5j	eyJjYXJ0Ijp7fX0:1wKHGZ:345yZOZCSyqyMYfzZao98pAo_Abt2-iwot-ZZol6R-w	2026-05-19 15:00:55.700521+00
h825nyphegijxqwaninzohg893nv30ro	eyJjYXJ0Ijp7fX0:1wKHGZ:345yZOZCSyqyMYfzZao98pAo_Abt2-iwot-ZZol6R-w	2026-05-19 15:00:55.890515+00
m55z2ep2b5n9jfzjga6kwhndt6hiyizx	eyJjYXJ0Ijp7fX0:1wKHGZ:345yZOZCSyqyMYfzZao98pAo_Abt2-iwot-ZZol6R-w	2026-05-19 15:00:55.994034+00
lju18ijparoiqpa9psboyekpx4h88smo	eyJjYXJ0Ijp7fX0:1wKHGa:VI0m8d_S180KblUCz_Px-SeFqKCSkeQE1BOv3C3jo8Y	2026-05-19 15:00:56.098084+00
m4tz6ld2kbk2eld1cm3sxh94whg7200v	eyJjYXJ0Ijp7fX0:1wKHGa:VI0m8d_S180KblUCz_Px-SeFqKCSkeQE1BOv3C3jo8Y	2026-05-19 15:00:56.290577+00
66zonjqhh1p9h1fbp626p0g4vuhtjff1	eyJjYXJ0Ijp7fX0:1wKHGa:VI0m8d_S180KblUCz_Px-SeFqKCSkeQE1BOv3C3jo8Y	2026-05-19 15:00:56.393844+00
kubfoxzu7ti0urbs7aibg8mde46r74az	eyJjYXJ0Ijp7fX0:1wKHGa:VI0m8d_S180KblUCz_Px-SeFqKCSkeQE1BOv3C3jo8Y	2026-05-19 15:00:56.495765+00
4r0w5pj7my4jqy7xtxf7hrn4182pmp5n	eyJjYXJ0Ijp7fX0:1wKHGc:mUO-D07ZdS0NVFySNTLt52UohFze-iI8A4noWHjz18A	2026-05-19 15:00:58.544016+00
hxivvhig2r1nd68o3alb6qtjuv6zmd46	eyJjYXJ0Ijp7fX0:1wKHGc:mUO-D07ZdS0NVFySNTLt52UohFze-iI8A4noWHjz18A	2026-05-19 15:00:58.691682+00
3q5kmhu8t895cnvj0ad6sbk2pd362ulv	eyJjYXJ0Ijp7fX0:1wKHGc:mUO-D07ZdS0NVFySNTLt52UohFze-iI8A4noWHjz18A	2026-05-19 15:00:58.793367+00
5x2dp1bzrmy2ua54cm2hkeoik1mtl2ka	eyJjYXJ0Ijp7fX0:1wKHGc:mUO-D07ZdS0NVFySNTLt52UohFze-iI8A4noWHjz18A	2026-05-19 15:00:58.895919+00
zpa9goo4lsc4yiodsu9cndg7ux0srcgw	eyJjYXJ0Ijp7fX0:1wKHGd:xtvgSmmaOaUoLN9Id2RzF3T2fifnvioqH-aTNmzkz-Q	2026-05-19 15:00:59.081535+00
wsotx5webe8tmvusufyajvdzrixkwo6r	eyJjYXJ0Ijp7fX0:1wKHGd:xtvgSmmaOaUoLN9Id2RzF3T2fifnvioqH-aTNmzkz-Q	2026-05-19 15:00:59.193003+00
as7dlpdwxlxhul615nlikrkwd37wv5j2	eyJjYXJ0Ijp7fX0:1wKHGd:xtvgSmmaOaUoLN9Id2RzF3T2fifnvioqH-aTNmzkz-Q	2026-05-19 15:00:59.293651+00
nodson2fxv3vxorrpx35qnmibn61ts68	eyJjYXJ0Ijp7fX0:1wKHGd:xtvgSmmaOaUoLN9Id2RzF3T2fifnvioqH-aTNmzkz-Q	2026-05-19 15:00:59.399161+00
2saicwy6akaxtxbb2bo2ii9okan0arom	eyJjYXJ0Ijp7fX0:1wKHGf:-qin3_CWwNgjEMLn252x0zTs_JdDchi4xvkcBQBl830	2026-05-19 15:01:01.580941+00
i85zxrhpdoyvurm5zurnixzmynqg1j5k	eyJjYXJ0Ijp7fX0:1wKHGf:-qin3_CWwNgjEMLn252x0zTs_JdDchi4xvkcBQBl830	2026-05-19 15:01:01.700169+00
mdjs3x4hkhkisev2m4f3epfuc8zp2rb6	eyJjYXJ0Ijp7fX0:1wKHGf:-qin3_CWwNgjEMLn252x0zTs_JdDchi4xvkcBQBl830	2026-05-19 15:01:01.893553+00
5kxvjr23yrzqg34985pzalsppzqfwt1r	eyJjYXJ0Ijp7fX0:1wKHGg:jeVrftoTx0R1MZgK1M1hQZDvT_c7as78T6_9Q1uhpjw	2026-05-19 15:01:02.081473+00
8vz9cdhha4nvwex8dmp654j5r9fq9if2	eyJjYXJ0Ijp7fX0:1wKHGg:jeVrftoTx0R1MZgK1M1hQZDvT_c7as78T6_9Q1uhpjw	2026-05-19 15:01:02.199655+00
obccddy3g6fang5cjg1dmzv5r45ylt8o	eyJjYXJ0Ijp7fX0:1wKHGg:jeVrftoTx0R1MZgK1M1hQZDvT_c7as78T6_9Q1uhpjw	2026-05-19 15:01:02.397313+00
wlb8r11p7q88aoip9lmk35qbuknukek5	eyJjYXJ0Ijp7fX0:1wKHGg:jeVrftoTx0R1MZgK1M1hQZDvT_c7as78T6_9Q1uhpjw	2026-05-19 15:01:02.581672+00
i7gfq2ia12e47gvlbf3uu71hep564leh	eyJjYXJ0Ijp7fX0:1wKHGg:jeVrftoTx0R1MZgK1M1hQZDvT_c7as78T6_9Q1uhpjw	2026-05-19 15:01:02.699915+00
w6hikmj91hyhi2tl0shtgpnb6cwb0au2	eyJjYXJ0Ijp7fX0:1wKHGg:jeVrftoTx0R1MZgK1M1hQZDvT_c7as78T6_9Q1uhpjw	2026-05-19 15:01:02.893928+00
ieeaxhgz1t3ysveuzm9erdsjfk5itenb	eyJjYXJ0Ijp7fX0:1wKHGh:Bxyzlaw_C1d92z59VGJOpeKgJ-kGWDv2ZUI4aZVHHXo	2026-05-19 15:01:03.003837+00
687ibhz2ymqlii5wcn3jut2wxjtoos5c	eyJjYXJ0Ijp7fX0:1wKHGh:Bxyzlaw_C1d92z59VGJOpeKgJ-kGWDv2ZUI4aZVHHXo	2026-05-19 15:01:03.200787+00
9nz3yzan8aa5wnqjjm1ohz5f0lddlu0e	eyJjYXJ0Ijp7fX0:1wKHGh:Bxyzlaw_C1d92z59VGJOpeKgJ-kGWDv2ZUI4aZVHHXo	2026-05-19 15:01:03.393818+00
539pg2x4zhnfkzxeoc08x91oj3zphvxl	eyJjYXJ0Ijp7fX0:1wKHGh:Bxyzlaw_C1d92z59VGJOpeKgJ-kGWDv2ZUI4aZVHHXo	2026-05-19 15:01:03.501665+00
m7pdw0344rqct8u2n32miob2724d4kpv	eyJjYXJ0Ijp7fX0:1wKHGh:Bxyzlaw_C1d92z59VGJOpeKgJ-kGWDv2ZUI4aZVHHXo	2026-05-19 15:01:03.694978+00
tit2dij7pn3v87pxmkz77bfejs9ter3m	eyJjYXJ0Ijp7fX0:1wKHGh:Bxyzlaw_C1d92z59VGJOpeKgJ-kGWDv2ZUI4aZVHHXo	2026-05-19 15:01:03.803731+00
tfbzlk5lxe2t8x4lnxkwlsdgq1w74vyw	eyJjYXJ0Ijp7fX0:1wKHGi:plEXQBb0AinIF2q9d-IkxkNXTQdMslt6Hx_ns5dCvQo	2026-05-19 15:01:04.002266+00
bps6wu1mu7q278jjm3xlnax8jilwjqqg	eyJjYXJ0Ijp7fX0:1wKHGi:plEXQBb0AinIF2q9d-IkxkNXTQdMslt6Hx_ns5dCvQo	2026-05-19 15:01:04.099078+00
kydisvh9svk2ydumn36dytmzo2gjkpji	eyJjYXJ0Ijp7fX0:1wKHGi:plEXQBb0AinIF2q9d-IkxkNXTQdMslt6Hx_ns5dCvQo	2026-05-19 15:01:04.29523+00
tuzysfuj8s16fprhlocgcc8ov4u63ag4	eyJjYXJ0Ijp7fX0:1wKHGi:plEXQBb0AinIF2q9d-IkxkNXTQdMslt6Hx_ns5dCvQo	2026-05-19 15:01:04.396939+00
eb7r5sdu91nplc6y74o9x54x8w29wj7x	eyJjYXJ0Ijp7fX0:1wKHGi:plEXQBb0AinIF2q9d-IkxkNXTQdMslt6Hx_ns5dCvQo	2026-05-19 15:01:04.591282+00
3cq6otttlcyus2gykaskebsfrmcyhyvb	eyJjYXJ0Ijp7fX0:1wKHGi:plEXQBb0AinIF2q9d-IkxkNXTQdMslt6Hx_ns5dCvQo	2026-05-19 15:01:04.698264+00
oyjlssdh238ycig5okgyrohzhaabwkmk	eyJjYXJ0Ijp7fX0:1wKHGi:plEXQBb0AinIF2q9d-IkxkNXTQdMslt6Hx_ns5dCvQo	2026-05-19 15:01:04.886639+00
5hckt4kfq80mtsmvkhj1190vt7d9y3b5	eyJjYXJ0Ijp7fX0:1wKHGi:plEXQBb0AinIF2q9d-IkxkNXTQdMslt6Hx_ns5dCvQo	2026-05-19 15:01:04.996634+00
uic82b9xidw0nfia3jpfe64znry11z76	eyJjYXJ0Ijp7fX0:1wKHGj:MtcQZfg2DYWM94Oi8IWKTWa1UlXUeTj7ZZdVW65_Qoc	2026-05-19 15:01:05.101885+00
dkiovnjo44384u0re2d6p2ngf83jngeq	eyJjYXJ0Ijp7fX0:1wKHGp:_WSkSWmohMsDfvKo0aDYj3ECVbzoxT2fFZXohL0sFao	2026-05-19 15:01:11.369929+00
gu17aic75eh3u5uptp1owvlnisdqa2u4	eyJjYXJ0Ijp7fX0:1wKHH3:vWt9ypl-elEa3vWUjreABxP2IOgAux7XKD-0f4wB4Ic	2026-05-19 15:01:25.124207+00
2yssnnbrvqssjq2cwfmke2r5uks9use7	eyJjYXJ0Ijp7fX0:1wKHHC:KGkEWLJudXOFLUyIVyzbszNLWd-ualO_RJbNP4vKgF0	2026-05-19 15:01:34.033654+00
c0r0co65wx22tutefx5dm5k5e35h6b1f	eyJjYXJ0Ijp7fX0:1wKHHF:sm988nOvxhd72xjwFop3emJYGHI4asZyFeUh6bdFjsw	2026-05-19 15:01:37.83084+00
1hrk89h7cyi3aul582c3932oxbdiqifs	eyJjYXJ0Ijp7fX0:1wKHJJ:5iwUsaleq5aMMfVdn1qGTp-2Ip-4ori5gXJrotrmsSg	2026-05-19 15:03:45.586708+00
6i69czg2sooic4ga5jvlnbeg6780q9vr	eyJjYXJ0Ijp7fX0:1wKHL8:4XZn6inR4MgZwwqnCO-fIvX2FcSAfKy1RO-Ymg2JY8A	2026-05-19 15:05:38.234008+00
z3n2r313me2iszz1lo05692ye0339yp4	eyJjYXJ0Ijp7fX0:1wKHXZ:ypykkPFnYKOcNSymuEdLZAzo0AVjPm1MCGwnx-FkenM	2026-05-19 15:18:29.642984+00
lh0vnofb3o37pdoijq6lovktkzwrab5j	eyJjYXJ0Ijp7fX0:1wKHol:P_1tYu7OGQFk9B_y46mjYY-U56kGQj12g641852verw	2026-05-19 15:36:15.387891+00
1v5biub4cy9hn7ijim3s9h3igipc3kq5	eyJjYXJ0Ijp7fX0:1wKISl:E-81xnRYh7wA55QkIph4dxKejkb8YS2UQhQTMTR-ge4	2026-05-19 16:17:35.515719+00
jg6f79b2oy12inb7zp9f1utgd9ynxhkx	eyJjYXJ0Ijp7fX0:1wKIT3:dej9MflR4_Wnwk-LLB46kMDCpdulFeHuoKL4fSqhwBE	2026-05-19 16:17:53.619259+00
rg57amudsognpby36wdnsmgrt197mn09	eyJjYXJ0Ijp7fX0:1wKIZX:ZiBH0EDJGmmx6YrGxIfUVaLNZHEIfmYrjp72OMUgkGE	2026-05-19 16:24:35.292781+00
7ebt3ttcwo52k3v8z5euiy5wspd4qnqc	eyJjYXJ0Ijp7fX0:1wKIZl:DjhAmuxNeL6u1nhxZkn-uKEx2sUoP3f0KgGmRor6uFA	2026-05-19 16:24:49.293371+00
inb1u6m2txez67vhtoplbrcgsa1z5c77	eyJjYXJ0Ijp7fX0:1wKJBn:yEYEOCWzJ-MktvBO7_bbJ8G8TQyFRAZgHreGusOP4x0	2026-05-19 17:04:07.416233+00
yfe56xf8e35n840ubnkq9mfuen34c9r9	eyJjYXJ0Ijp7fX0:1wKJDH:7EeHs3d2o4BPGi_4ct8tbSfVA2fs4dznNGLNI-k-4c0	2026-05-19 17:05:39.04418+00
gf2wgvx8yjjydub1iw0o41k6rbu98mjf	eyJjYXJ0Ijp7fX0:1wKJEL:8jmu7IiqTzgergbEciyjue6iL6rWEYbZdmsWd00VlCk	2026-05-19 17:06:45.882954+00
3zbr9jayjcrgghlz9b88v29a2vxwsqyw	eyJjYXJ0Ijp7fX0:1wKJHh:AU7JCnW2uFRasWjUvmJUoUJ_eZTvzaBgANfYk4AXoh8	2026-05-19 17:10:13.439654+00
al2zy6j3ev27q8v9gdx5ulmyo1b1kmth	.eJyrVkpOLCpRsqpWMgcRhaWJeSWZJZVKVoY6SgVFmcmpSlZKxuZm5noGBkq1OkqGxjhVGRoAAUyZJU5lpghFprhtRBhlhE8RVI0ZTjVmUDW1tQCELUJD:1wKJa1:6f0_1y11mxXQO7PxGfQ_8uRePAaPECxccRvpmgyEkF4	2026-05-19 17:29:09.991115+00
yq9wp0f1eistiuclkmzahn5p0jailnpa	eyJjYXJ0Ijp7fX0:1wKJbq:REnZVyPzhzWc9ZzKRmh3QrEAKSVjpNDjHGAPvU7XxX8	2026-05-19 17:31:02.780874+00
v6q6mom6fbi9j7nnsbafwuvup2qrsrg6	eyJjYXJ0Ijp7fX0:1wKJyw:HMBo_vB9chFNsDDD_6Mg-MuDxAsK1Z5uHWYGDVgofsw	2026-05-19 17:54:54.089772+00
m2vuilh7w8040ag5qjsk4gmqhqrc9vx9	eyJjYXJ0Ijp7fX0:1wKK36:eaIhl_Pcz_ur-EjKM5SGprYzgqiHJVQQTyfQd9qYitk	2026-05-19 17:59:12.188398+00
wgnm58sklf8o1vxpbif1jo7v6rt02fie	eyJjYXJ0Ijp7fX0:1wKKXW:DCFSTXnNrTQX25qYDMFhwLhCqCz5wYxPLIzNjAuJqpQ	2026-05-19 18:30:38.790984+00
kck6fnye7iqsbx4pg8a5qitklz2hdh9o	eyJjYXJ0Ijp7fX0:1wKMuJ:lj-G_uhBmRjMUWOCyiSEBE0IN7dh1Hgh8qpWEqi8xsw	2026-05-19 21:02:19.134713+00
jhyr4gj82pbn6xjfjgm0gsw2inacx0nz	eyJjYXJ0Ijp7fX0:1wKMwv:11EwjsJI2rD9ZT7_vS3WBxj4ExK3xTvsmJELGKcU444	2026-05-19 21:05:01.422057+00
vv9dl8fqketx9cgemegrzz0mikpwelr0	.eJyrVkpOLCpRsqpWMgcRhaWJeSWZJZVKVoY6SgVFmcmpSlZKxuZm5noGBkq1OkqGxjhVGRoAAUyZJU5lpghFprhtRBhlhE8RVI0ZTjVmUDW1tQCELUJD:1wKNQp:v_0bLyRVYMDaZLNvHJRnJAvc3KwT1OtnUJZxByRyf1Q	2026-05-19 21:35:55.25896+00
6870y4t6cqq9msa9ganfhj2y2td3016u	eyJjYXJ0Ijp7fX0:1wKNVu:2qzNkX9fOPPD504nJUX3TIIJOWjj7SO7yP9-NPnpsLU	2026-05-19 21:41:10.541823+00
cwmgdckves465crbbv6bcqkyl0kyybhl	eyJjYXJ0Ijp7fX0:1wKNVx:MczEHmyckAsyTW2dbBeIyJaCzzYcjA5uVQAvHKfZios	2026-05-19 21:41:13.192031+00
6mla9bub09tul01bjdxm5s7zuazfwz67	eyJjYXJ0Ijp7fX0:1wKOFY:4FgWaT3uqjJfkano-DGroQ8-DKkK1GZWWg2T3Nm-XRw	2026-05-19 22:28:20.087866+00
bkp2yckuktp22p0q53auswwe0qv6ffva	eyJjYXJ0Ijp7fX0:1wKOGJ:abjhHVoxPsBO23ZTx7VXmyfBdgTSLYNvvDo2LyBOIBY	2026-05-19 22:29:07.230109+00
bk1x5dg2eeat62hiwmrewcntxpn7zo0s	eyJjYXJ0Ijp7fX0:1wKOfc:6hIBIkbiJ3fbYx-nVu9kPnlVDrcSXHKB-FA49RIGpGk	2026-05-19 22:55:16.738941+00
pf0uigma42xt0cnqk22q8xt8kg2pr9kr	eyJjYXJ0Ijp7fX0:1wKPNu:73gCVnEhGOHFZGUy-E1UZzlOZOS14Hkx0mipPCkDZsI	2026-05-19 23:41:02.916763+00
qe8p3ju67cc1m32nqanlyayf2a6kc12u	eyJjYXJ0Ijp7fX0:1wKPe1:PqfAff6wsUK1JAShpO2OH1OMq5wV112V0ZhUTxQZITQ	2026-05-19 23:57:41.294797+00
x3at78xajm3qqi04s52hm7ljbra6in28	eyJjYXJ0Ijp7fX0:1wKPq5:810t5O49M3jBn66BoffrJ0nxdy3TYspzrCOmVmii0i0	2026-05-20 00:10:09.104065+00
1bsr2iln0mok9an40xcp1gpkqv5mpiy9	eyJjYXJ0Ijp7fX0:1wKPqG:mOveD8IPkvcqd_YQlGNjBy3Tr-IsD8tU1w_30UP3JDs	2026-05-20 00:10:20.492345+00
t5w5q6ks4elm427ogrhphkknxzwprtee	eyJjYXJ0Ijp7fX0:1wKQm6:TLMEHR7grRGkc38hGK4N63wtWurd699kvtgRp2meT7w	2026-05-20 01:10:06.720677+00
bskmrhh14repzoe21iqjjoqhj4bwudfd	eyJjYXJ0Ijp7fX0:1wKQp4:SW9mRhwngihcdvnp1fJL9Z2PUytFAPIYu2UEqzwkFgQ	2026-05-20 01:13:10.648359+00
4asa2jn8gevh7zkdvoscm2w51dxbcae5	eyJjYXJ0Ijp7fX0:1wKSim:FnkckVH2j3Qk607kClDZJHGdWHLBfUQi782WQLUyDtY	2026-05-20 03:14:48.780139+00
ihjt8zkuf25loyhxx4msiekkieirlaue	eyJjYXJ0Ijp7fX0:1wKSs1:2uzkaSWeRJ1fmAKAeO6_0ljVYSCcaMQB5joiElxMigg	2026-05-20 03:24:21.241608+00
hj98vgkvujtpbsgjpy52zl1yitktuc6t	eyJjYXJ0Ijp7fX0:1wKSs1:2uzkaSWeRJ1fmAKAeO6_0ljVYSCcaMQB5joiElxMigg	2026-05-20 03:24:21.390458+00
wqhdpg32v7gti7ugtjqllcvvvblw9u65	eyJjYXJ0Ijp7fX0:1wKTVx:hp3HDYGyZ9pWrrbk_-w3GEazJWQTS8F4XQ27LtBwMmg	2026-05-20 04:05:37.800946+00
o9qy9mq67dl7dxvgfszbx0l8mtgq1ct9	eyJjYXJ0Ijp7fX0:1wKTvh:bj3D4Knx5ynoznOwxUeN9OeErNg7N7P2Nja4phEKWdA	2026-05-20 04:32:13.100123+00
0kiurujsm3607kfsu3myw8r8sf2a2x2v	eyJjYXJ0Ijp7fX0:1wKTvh:bj3D4Knx5ynoznOwxUeN9OeErNg7N7P2Nja4phEKWdA	2026-05-20 04:32:13.345601+00
4uzstmmpoer9769r22djwj2v0zgrl08o	eyJjYXJ0Ijp7fX0:1wKU05:vQGjwF3LHj39irCWKVQLPXk89FNhaP0Fx5BOtt-1wXU	2026-05-20 04:36:45.386973+00
da5njvleg7sgohi6jgxltc5s1b9q1bvl	eyJjYXJ0Ijp7fX0:1wKU0P:tovN4T6MK01O3r0Notkl4GKdokU9coj6p4ukHZhESYs	2026-05-20 04:37:05.304497+00
fwy8trhmzp9dfcipfqlzbps1n2ysjfkj	eyJjYXJ0Ijp7fX0:1wKU6c:Wcxxk0O2p8S54jLz2PP8ByLLs8r7wi-4qUhsZ7eHpeI	2026-05-20 04:43:30.481319+00
dgu8n2p8jjxu69aw33ddv3w2w2451m5q	eyJjYXJ0Ijp7fX0:1wKUQj:PJGeH4Tof-1Zw2yFovKF9jwb4yGuNG_C_QO3TwCSARY	2026-05-20 05:04:17.997637+00
43z6zkvl8jl4fsfkqepv862gam8kqkoa	eyJjYXJ0Ijp7fX0:1wKVDb:pwnYuH_-Ee_bitv7DWd0T6IECTQ_KqcNdBugcpTgoyk	2026-05-20 05:54:47.553343+00
htwomz87jcw36c1rl3h8nogwwo70au1i	eyJjYXJ0Ijp7fX0:1wKVYw:OKnRv5gWjxtO8slwolRf4nI5Btb4BZUbgpPcMMlKJuc	2026-05-20 06:16:50.783942+00
l4vy2rhf8215meylhsbbwdcnbsbgfl62	eyJjYXJ0Ijp7fX0:1wKVxU:cMtV71Mgt0WHdcjr9F9JDz8sLdXfysgoi_zJJ95RqFI	2026-05-20 06:42:12.949465+00
xdw0kgvczwmlg0gj5qynd8j7lwp0xxq3	.eJxVjDsOgzAQBe-ydWTZ-E-ZnjOg9drEJJGRbKgQd0-QaGjfzLwdCOsK_X48YMRtzePWUh3nCD1YuG0B6ZPKCeIby2thtJS1zoGdCrtoY8MS0_d5ubeDjC3_axlsF0j4qMjIKcjovPZCdyk6nih41ByTUCQ0GTcpxYVBctJJ4S2XRsHxAy-SOpI:1wKWQu:OwPNhTTFECucKm4_p1_fuGMKWpTQwnWTEqFFpvTL2OM	2026-05-20 07:12:36.035395+00
p2n24i18q9w30f9ymo4jfl7cmcdhi6u3	eyJjYXJ0Ijp7fX0:1wKWSq:Gl8I_lPGthmB88FLjyC22JsVm0KHIr2i72CahDMJ4wk	2026-05-20 07:14:36.296896+00
fpak4ysi5rcbl2qfdt12t7uliwgelfp8	eyJjYXJ0Ijp7fX0:1wKXci:uFNuIN1-4YyQ0XeY54KGfoCBArCFWb20dxC3PEipo4U	2026-05-20 08:28:52.232413+00
wzc5bibd36m54raltkq85d2ywxdw31s3	eyJjYXJ0Ijp7fX0:1wKYKU:pia77DRfeiID6Md-UfwJzVib25zufwVcP6LrgZQNzOE	2026-05-20 09:14:06.338735+00
iku332n8eh79edjqp1hcaegrb950y764	.eJyrVkpOLCpRsqpWMjQFkYWliXklmSWVSlaGOkoFRZnJqUpWSsYGBgZ6BgZKtTpKhsY4VRkaIJSZ4VRlBldjhM8-mHWWOBWZwhWZ4zbI3MwcrKi2FgB3U0JD:1wKZAR:yDsbuYLgy_VjyZKhKW-jdbkM3erzX_jbPTfYj3BIkjg	2026-05-20 10:07:47.484916+00
tl509v00a9lsjrbp02gcbrf64ff9yk9m	eyJjYXJ0Ijp7fX0:1wKZWW:i4FCR1yVaP9y6KjsKHimlT4cogfkPa20ADU4U-TY-wU	2026-05-20 10:30:36.595173+00
f1427k2j8sil39gdzzu2b5tdjb1ayg2m	eyJjYXJ0Ijp7fX0:1wKaBK:Jh3J9Ivj4ZAo01tnXBgWGem1h2e9xTnY1YyJPrIn8Fw	2026-05-20 11:12:46.573605+00
sofs89yyg061yr3qwnv2x0t94g2cblrl	eyJjYXJ0Ijp7fX0:1wKaBO:39Uu-h0087WFs77obPfzMHa9aGx7Z1efZ2sDEZt8ENY	2026-05-20 11:12:50.092466+00
s887ah674iob4bea33k2ot6jr0nocrdv	.eJyrVkpOLCpRsqpWMgcRhaWJeSWZJZVKVoY6SgVFmcmpSlZKxuZm5noGBkq1OkqGxjhVGRoAAUyZJU5lpghFprhtRBhlhE8RVI0ZTjVmUDW1tQCELUJD:1wKaj0:QrSSj7rqOc44GuWypXCL2m1d-atxXO7wf1XpYhDvt0E	2026-05-20 11:47:34.484552+00
\.


--
-- Data for Name: shop_category; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_category (id, name, slug) FROM stdin;
1	Декоративные кустарники	dekorativnye-kustarniki
2	Лиственные	listvennye
3	Плодовые	plodovye
4	Тропические	tropicheskie
5	Хвойные	hvojnye
\.


--
-- Data for Name: shop_coupon; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_coupon (id, code, discount, active, valid_from, valid_to) FROM stdin;
1	SALE20	10	t	2026-05-01 01:00:00+00	2027-05-01 01:00:00+00
\.


--
-- Data for Name: shop_favorite; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_favorite (id, created, product_id, user_id) FROM stdin;
1	2026-05-04 06:28:39.124908+00	7	8
2	2026-05-04 06:28:41.488982+00	4	8
3	2026-05-04 08:05:51.016406+00	19	9
4	2026-05-04 08:05:54.184631+00	10	9
5	2026-05-04 08:05:56.010749+00	14	9
\.


--
-- Data for Name: shop_order; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_order (id, first_name, last_name, phone, address, created, paid, user_id, comment, payment_method) FROM stdin;
1	Гемини		+17547555445	Респ. Башкортостан, г. Уфа, ул. Садовая, д. 47	2026-05-04 06:29:22.018857+00	f	8	нет	cash
2	Гемини		+17547555445	Респ. Башкортостан, г. Уфа, пр-т Октября, д. 118	2026-05-04 06:30:43.507846+00	f	8		card
3	Гемини		+17547555445	Респ. Башкортостан, г. Уфа, ул. Российская, д. 202	2026-05-04 06:31:51.731742+00	f	8		cash
4	Лук		+7745744344	Респ. Башкортостан, г. Уфа, ул. Плодовая, д. 17	2026-05-04 08:05:35.422108+00	f	9	аккуратнее	card
5	Лук		+7745744344	Респ. Башкортостан, г. Уфа, ул. Питомниковая, д. 1	2026-05-04 08:06:32.676282+00	f	9		cash
6	Лук		+7745744344	Респ. Башкортостан, г. Уфа, пр-т Октября, д. 118	2026-05-04 08:07:09.659831+00	f	9		card
7	Лук		+7745744344	Респ. Башкортостан, г. Уфа, ул. Садовая, д. 47	2026-05-04 08:08:01.578213+00	f	9		cash
8	Гемини		+17547555445	Респ. Башкортостан, г. Уфа, ул. Лесная, д. 3	2026-05-04 12:15:48.429035+00	f	8		cash
9	Гемини		+17547555445	Респ. Башкортостан, г. Уфа, ул. Дачная, д. 71	2026-05-04 14:23:29.457254+00	f	8	нет	cash
10	Гемини		+17547555445	Респ. Башкортостан, г. Уфа, ул. Лесная, д. 3	2026-05-05 04:28:25.718317+00	f	8		cash
11	5		54	Респ. Башкортостан, г. Уфа, ул. Лесная, д. 3	2026-05-05 06:07:03.791834+00	f	10		cash
\.


--
-- Data for Name: shop_orderitem; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_orderitem (id, price, quantity, order_id, product_id) FROM stdin;
1	3767.00	2	1	7
2	600.00	1	1	6
3	3000.00	1	2	15
4	2000.00	1	3	12
5	300.00	1	3	2
6	500.00	4	4	19
7	200.00	1	5	10
8	2000.00	2	6	12
9	10000.00	2	7	13
10	300.00	1	8	2
11	1500.00	2	9	8
12	500.00	1	10	19
13	450.00	1	11	1
\.


--
-- Data for Name: shop_otpcode; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_otpcode (id, code, created, is_used, user_id) FROM stdin;
1	618753	2026-05-04 12:14:16.566969+00	t	8
\.


--
-- Data for Name: shop_product; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_product (id, name, slug, image, description, price, available, created, category_id) FROM stdin;
8	Ель	el	media/products/Glauca_globosa_Pa3-1000x1500_qymfvd	Хвойная порода со светлой, лёгкой древесиной и равномерной структурой. Широко используется в строительстве, производстве бумаги и изготовлении музыкальных инструментов. Хорошо поддаётся обработке.	1500.00	t	2026-05-04 06:02:40.742588+00	5
3	Венге	venge		Тропическая порода из Африки с тёмно-коричневой древесиной и выраженным контрастным рисунком. Высокая прочность и устойчивость к износу. Используется в элитной мебели и напольных покрытиях.	4600.00	t	2026-05-04 05:59:37.897947+00	4
2	Береза	bereza	media/products/02448_bereza_golden_dream_004_i5jaiw	Светлая, легко обрабатываемая древесина с однородной текстурой. Широко применяется в мебельном производстве, отделке и изготовлении фанеры. Одна из самых распространённых пород в России.	300.00	t	2026-05-04 05:59:04.829397+00	2
4	Вишня	vishnya	media/products/vishnya-shokoladnica_zcgsyd	Плодовое дерево с красновато-розовой древесиной благородного оттенка. Ценится в столярном деле за красивую текстуру и лёгкость полировки. Плоды — сочные кисло-сладкие ягоды.	225.00	t	2026-05-04 06:00:11.092893+00	3
5	Груша	grusha	media/products/Sort-grushi-Pamiat-Zhegalova_lchqtx	Плодовая порода с плотной, мелкозернистой древесиной розоватого тона. Отлично подходит для резьбы, токарных работ и изготовления музыкальных инструментов. Даёт сладкие сочные плоды.	3000.00	t	2026-05-04 06:00:48.986275+00	3
7	Дёрен	dyoren	media/products/85_pwaala	Декоративный кустарник с яркими побегами красного или жёлтого цвета, эффектными в зимнее время. Быстрорастущий, морозостойкий, неприхотлив к почве. Идеален для групповых посадок.	3767.00	t	2026-05-04 06:01:59.086498+00	1
6	Дуб	dub	media/products/Quercus-robur-5_qbldcx	Твёрдая, долговечная древесина с выраженной текстурой и высокой стойкостью к влаге. Классический материал для мебели, паркета, бочек и несущих конструкций. Символ прочности и надёжности.	600.00	t	2026-05-04 06:01:18.183411+00	2
14	Палисандр	palisandr		Ценная тропическая древесина с богатой палитрой от шоколадного до фиолетового оттенка. Очень плотная и твёрдая. Применяется в производстве музыкальных инструментов и дорогой мебели.	8000.00	t	2026-05-04 06:10:33.690753+00	4
1	Барбарис	barbaris	media/products/red-roket-2_yxhatj	Колючий кустарник с яркой осенней листвой и декоративными ягодами. Отлично подходит для живых изгородей и бордюров. Неприхотлив, устойчив к морозам и засухе.	450.00	t	2026-05-04 05:58:31.982498+00	1
10	Клён	klyon	media/products/2_b9h59w	Лиственная порода с твёрдой, светлой древесиной и красивым волнистым рисунком. Применяется в мебельном деле, производстве музыкальных инструментов и спортивного инвентаря.	200.00	t	2026-05-04 06:03:52.996979+00	2
15	Пихта	pihta	media/products/WhatsApp_Image_2024-06-30_at_10.38.121-1000x1500_kiprkv	Хвойное дерево с мягкой, лёгкой древесиной без смоляных ходов. Не имеет резкого запаха, подходит для внутренней отделки, тары и целлюлозного производства.	3000.00	t	2026-05-04 06:11:00.482486+00	5
9	Кедр	kedr	media/products/2308202111_WhatsApp_Image_2021-08-23_at_14.47.01-1000x1500_llm1f4	Хвойное дерево с ароматной, мягкой древесиной и выраженными антисептическими свойствами. Высоко ценится в отделке бань, изготовлении мебели и строительстве. Орехи — ценный пищевой продукт.	4500.00	t	2026-05-04 06:03:22.1628+00	5
11	Липа	lipa	media/products/Greenspire3-1000x1500_gvplsv	Мягкая, однородная древесина белого цвета, легко поддающаяся резьбе. Традиционный материал для художественной резьбы, посуды и банной отделки. Липовый мёд считается одним из лучших.	900.00	t	2026-05-04 06:04:31.220335+00	2
12	Лиственница	listvennica	media/products/WhatsApp_Image_2024-06-29_at_17.29.06-1000x1500_rphszw	Самая прочная и влагостойкая хвойная порода. Не гниёт в воде, долговечна без специальной обработки. Идеальна для наружных конструкций, террас, причалов и фасадов.	2000.00	t	2026-05-04 06:05:18.41729+00	5
23	Ясень	yasen	media/products/1903202309_KellysGold1-1000x1500_wj0v50	Твёрдая, упругая древесина с красивой выраженной текстурой. Отличная ударная вязкость. Применяется в производстве спортивного инвентаря, рукояток инструментов, мебели и паркета.	1500.00	t	2026-05-04 06:15:20.087906+00	2
22	Яблоня	yablonya	media/products/0408202310_photo_5359536801183813087_y-1000x1500_lnqssm	Самое распространённое плодовое дерево в России. Твёрдая, плотная древесина с тонкой текстурой, хороша для резьбы и токарки. Множество сортов с разными сроками созревания.	2000.00	t	2026-05-04 06:14:50.935166+00	3
21	Черешня	chereshnya	media/products/chrome_2023-03-10_04-26-04_vriuiz	Плодовое дерево с тёплой розовато-коричневой древесиной, темнеющей со временем. Популярна в мебельном производстве за благородный оттенок. Крупные сладкие ягоды созревают в начале лета.	6700.00	t	2026-05-04 06:14:11.397472+00	3
20	Тик	tik	media/products/2710202101_1-1000x1500_ra7rd5	Тропическая порода с высоким содержанием природных масел, что обеспечивает исключительную влагостойкость. Золотисто-коричневый цвет. Классический материал для палуб, садовой мебели и ванных комнат.	2565.00	t	2026-05-04 06:13:48.937925+00	4
19	Спирея	spireya	media/products/50f9e73f576e07e66d0072716cdc72b1_ey0tfu	Компактный декоративный кустарник с обильным цветением белого или розового цвета. Неприхотлива, быстро растёт, легко формируется стрижкой. Подходит для бордюров и невысоких изгородей.	500.00	t	2026-05-04 06:13:22.493308+00	1
18	Сосна	sosna	media/products/0805202310_photo_2023-05-09_00-13-20_3-1000x1500_iki6lj	Самая распространённая хвойная порода в строительстве. Доступная, лёгкая, смолистая древесина с хорошей прочностью. Применяется в каркасном строительстве, мебели, отделке и столярке.	1000.00	t	2026-05-04 06:12:49.539792+00	5
17	Слива	sliva	media/products/dekorativnaya-sliva-krasnolistnaya-E2E01B3_mggsen	Плодовое дерево с твёрдой красновато-коричневой древесиной. Используется в мелкой столярке и токарных изделиях. Даёт сочные плоды, применяемые в кулинарии и заготовках.	2499.00	t	2026-05-04 06:12:17.419898+00	3
16	Сирень	siren	media/products/2210202211_WhatsApp_Image_2022-08-18_at_13.47.07-1000x1500_dfag5o	Крупный декоративный кустарник с пышным ароматным цветением весной. Множество сортов с белыми, розовыми и фиолетовыми соцветиями. Морозоустойчива, долговечна, минимальный уход.	2656.00	t	2026-05-04 06:11:41.226796+00	1
13	Махогони	mahogoni	media/products/Sort-slivy-Manchzhurskaia-krasavitca_er9jpb	Элитная тропическая порода красно-коричневого цвета с характерным золотистым блеском. Легко обрабатывается, стабильна при перепадах влажности. Используется в люксовой мебели и судостроении.	10000.00	t	2026-05-04 06:10:01.880957+00	4
\.


--
-- Data for Name: shop_profile; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_profile (id, phone, user_id) FROM stdin;
7		7
8	+17547555445	8
9	+7745744344	9
10	54	10
\.


--
-- Data for Name: shop_review; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shop_review (id, text, rating, created, product_id, user_id) FROM stdin;
1	качество хуже не куда	3	2026-05-04 06:30:00.181479+00	7	8
2	прекрасно!	5	2026-05-04 06:30:20.463348+00	6	8
3	Отлично! я даже не ожидал	5	2026-05-04 06:31:00.7878+00	15	8
4	нет	1	2026-05-04 06:32:03.460543+00	12	8
5	Буду заказывать!	5	2026-05-04 06:32:28.93192+00	2	8
6	Качество отличное!	5	2026-05-04 08:06:20.08733+00	19	9
7	не прижился:(	2	2026-05-04 08:06:47.589779+00	10	9
8	уже лучше	4	2026-05-04 08:07:26.293622+00	12	9
9	норм, но дороговато)	4	2026-05-04 08:08:27.063085+00	13	9
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 10, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 50, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- Name: shop_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_category_id_seq', 5, true);


--
-- Name: shop_coupon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_coupon_id_seq', 1, true);


--
-- Name: shop_favorite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_favorite_id_seq', 5, true);


--
-- Name: shop_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_order_id_seq', 11, true);


--
-- Name: shop_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_orderitem_id_seq', 13, true);


--
-- Name: shop_otpcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_otpcode_id_seq', 1, true);


--
-- Name: shop_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_product_id_seq', 23, true);


--
-- Name: shop_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_profile_id_seq', 10, true);


--
-- Name: shop_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shop_review_id_seq', 9, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: shop_category shop_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_category
    ADD CONSTRAINT shop_category_pkey PRIMARY KEY (id);


--
-- Name: shop_category shop_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_category
    ADD CONSTRAINT shop_category_slug_key UNIQUE (slug);


--
-- Name: shop_coupon shop_coupon_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_coupon
    ADD CONSTRAINT shop_coupon_code_key UNIQUE (code);


--
-- Name: shop_coupon shop_coupon_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_coupon
    ADD CONSTRAINT shop_coupon_pkey PRIMARY KEY (id);


--
-- Name: shop_favorite shop_favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_favorite
    ADD CONSTRAINT shop_favorite_pkey PRIMARY KEY (id);


--
-- Name: shop_favorite shop_favorite_user_id_product_id_6d06c806_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_favorite
    ADD CONSTRAINT shop_favorite_user_id_product_id_6d06c806_uniq UNIQUE (user_id, product_id);


--
-- Name: shop_order shop_order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_order
    ADD CONSTRAINT shop_order_pkey PRIMARY KEY (id);


--
-- Name: shop_orderitem shop_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_orderitem
    ADD CONSTRAINT shop_orderitem_pkey PRIMARY KEY (id);


--
-- Name: shop_otpcode shop_otpcode_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_otpcode
    ADD CONSTRAINT shop_otpcode_pkey PRIMARY KEY (id);


--
-- Name: shop_product shop_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_product
    ADD CONSTRAINT shop_product_pkey PRIMARY KEY (id);


--
-- Name: shop_product shop_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_product
    ADD CONSTRAINT shop_product_slug_key UNIQUE (slug);


--
-- Name: shop_profile shop_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_profile
    ADD CONSTRAINT shop_profile_pkey PRIMARY KEY (id);


--
-- Name: shop_profile shop_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_profile
    ADD CONSTRAINT shop_profile_user_id_key UNIQUE (user_id);


--
-- Name: shop_review shop_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_review
    ADD CONSTRAINT shop_review_pkey PRIMARY KEY (id);


--
-- Name: shop_review shop_review_product_id_user_id_34338eec_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_review
    ADD CONSTRAINT shop_review_product_id_user_id_34338eec_uniq UNIQUE (product_id, user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: shop_category_slug_4508178e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_category_slug_4508178e_like ON public.shop_category USING btree (slug varchar_pattern_ops);


--
-- Name: shop_coupon_code_42417dff_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_coupon_code_42417dff_like ON public.shop_coupon USING btree (code varchar_pattern_ops);


--
-- Name: shop_favorite_product_id_5d55ea00; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_favorite_product_id_5d55ea00 ON public.shop_favorite USING btree (product_id);


--
-- Name: shop_favorite_user_id_5f37df04; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_favorite_user_id_5f37df04 ON public.shop_favorite USING btree (user_id);


--
-- Name: shop_order_user_id_00aba627; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_order_user_id_00aba627 ON public.shop_order USING btree (user_id);


--
-- Name: shop_orderitem_order_id_2f1b00cf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_orderitem_order_id_2f1b00cf ON public.shop_orderitem USING btree (order_id);


--
-- Name: shop_orderitem_product_id_48153f22; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_orderitem_product_id_48153f22 ON public.shop_orderitem USING btree (product_id);


--
-- Name: shop_otpcode_user_id_51190b5c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_otpcode_user_id_51190b5c ON public.shop_otpcode USING btree (user_id);


--
-- Name: shop_product_category_id_14d7eea8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_product_category_id_14d7eea8 ON public.shop_product USING btree (category_id);


--
-- Name: shop_product_slug_30bd2d5d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_product_slug_30bd2d5d_like ON public.shop_product USING btree (slug varchar_pattern_ops);


--
-- Name: shop_review_product_id_f74dddfd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_review_product_id_f74dddfd ON public.shop_review USING btree (product_id);


--
-- Name: shop_review_user_id_02dce754; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX shop_review_user_id_02dce754 ON public.shop_review USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_favorite shop_favorite_product_id_5d55ea00_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_favorite
    ADD CONSTRAINT shop_favorite_product_id_5d55ea00_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_favorite shop_favorite_user_id_5f37df04_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_favorite
    ADD CONSTRAINT shop_favorite_user_id_5f37df04_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_order shop_order_user_id_00aba627_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_order
    ADD CONSTRAINT shop_order_user_id_00aba627_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_orderitem shop_orderitem_order_id_2f1b00cf_fk_shop_order_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_orderitem
    ADD CONSTRAINT shop_orderitem_order_id_2f1b00cf_fk_shop_order_id FOREIGN KEY (order_id) REFERENCES public.shop_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_orderitem shop_orderitem_product_id_48153f22_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_orderitem
    ADD CONSTRAINT shop_orderitem_product_id_48153f22_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_otpcode shop_otpcode_user_id_51190b5c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_otpcode
    ADD CONSTRAINT shop_otpcode_user_id_51190b5c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_product shop_product_category_id_14d7eea8_fk_shop_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_product
    ADD CONSTRAINT shop_product_category_id_14d7eea8_fk_shop_category_id FOREIGN KEY (category_id) REFERENCES public.shop_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_profile shop_profile_user_id_251f5ef7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_profile
    ADD CONSTRAINT shop_profile_user_id_251f5ef7_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_review shop_review_product_id_f74dddfd_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_review
    ADD CONSTRAINT shop_review_product_id_f74dddfd_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_review shop_review_user_id_02dce754_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shop_review
    ADD CONSTRAINT shop_review_user_id_02dce754_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict c32zyziezKNevcbsMO2YP6kstFfyR6XvZf3u3wj7CO5gdZDioKmOA3aCh1lmDyl

