# Generated by Django 5.2.13 on 2026-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_first_name_alter_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('card', 'Картой при получении')], default='cash', max_length=10, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
