# Generated by Django 5.2.13 on 2026-05-18 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_coupon_order_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'is_used', 'created'], name='shop_otpcod_user_id_795f14_idx'),
        ),
    ]
