# Generated by Django 5.2.13 on 2026-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_otpcode_shop_otpcod_user_id_795f14_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'category'], name='shop_produc_availab_16d7dc_idx'),
        ),
    ]
