# Generated by Django 5.2.13 on 2026-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_shop_produc_availab_16d7dc_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='code',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='code_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
